(function(b){b.extend(b.fn,{validate:function(c){if(this.length){var a=b.data(this[0],"validator");if(a)return a;this.attr("novalidate","novalidate");a=new b.validator(c,this[0]);b.data(this[0],"validator",a);a.settings.onsubmit&&(c=this.find("input, button"),c.filter(".cancel").click(function(){a.cancelSubmit=!0}),a.settings.submitHandler&&c.filter(":submit").click(function(){a.submitButton=this}),this.submit(function(d){function c(){if(a.settings.submitHandler){if(a.submitButton)var d=b("<input type='hidden'/>").attr("name",
a.submitButton.name).val(a.submitButton.value).appendTo(a.currentForm);a.settings.submitHandler.call(a,a.currentForm);a.submitButton&&d.remove();return!1}return!0}a.settings.debug&&d.preventDefault();if(a.cancelSubmit)return a.cancelSubmit=!1,c();if(a.form())return a.pendingRequest?(a.formSubmitted=!0,!1):c();a.focusInvalid();return!1}));return a}c&&c.debug&&window.console&&console.warn("nothing selected, can't validate, returning nothing")},valid:function(){if(b(this[0]).is("form"))return this.validate().form();
var c=!0,a=b(this[0].form).validate();this.each(function(){c&=a.element(this)});return c},removeAttrs:function(c){var a={},d=this;b.each(c.split(/\s/),function(b,c){a[c]=d.attr(c);d.removeAttr(c)});return a},rules:function(c,a){var d=this[0];if(c){var g=b.data(d.form,"validator").settings,e=g.rules,h=b.validator.staticRules(d);switch(c){case "add":b.extend(h,b.validator.normalizeRule(a));e[d.name]=h;a.messages&&(g.messages[d.name]=b.extend(g.messages[d.name],a.messages));break;case "remove":if(!a)return delete e[d.name],
h;var f={};b.each(a.split(/\s/),function(a,b){f[b]=h[b];delete h[b]});return f}}d=b.validator.normalizeRules(b.extend({},b.validator.metadataRules(d),b.validator.classRules(d),b.validator.attributeRules(d),b.validator.staticRules(d)),d);d.required&&(g=d.required,delete d.required,d=b.extend({required:g},d));return d}});b.extend(b.expr[":"],{blank:function(c){return!b.trim(""+c.value)},filled:function(c){return!!b.trim(""+c.value)},unchecked:function(b){return!b.checked}});b.validator=function(c,a){this.settings=
b.extend(!0,{},b.validator.defaults,c);this.currentForm=a;this.init()};b.validator.format=function(c,a){if(1==arguments.length)return function(){var a=b.makeArray(arguments);a.unshift(c);return b.validator.format.apply(this,a)};2<arguments.length&&a.constructor!=Array&&(a=b.makeArray(arguments).slice(1));a.constructor!=Array&&(a=[a]);b.each(a,function(a,b){c=c.replace(RegExp("\\{"+a+"\\}","g"),b)});return c};b.extend(b.validator,{defaults:{messages:{},groups:{},rules:{},errorClass:"error",validClass:"valid",
errorElement:"label",focusInvalid:!0,errorContainer:b([]),errorLabelContainer:b([]),onsubmit:!0,ignore:":hidden",ignoreTitle:!1,onfocusin:function(b){this.lastActive=b;this.settings.focusCleanup&&!this.blockFocusCleanup&&(this.settings.unhighlight&&this.settings.unhighlight.call(this,b,this.settings.errorClass,this.settings.validClass),this.addWrapper(this.errorsFor(b)).hide())},onfocusout:function(b){this.checkable(b)||!(b.name in this.submitted)&&this.optional(b)||this.element(b)},onkeyup:function(b){(b.name in
this.submitted||b==this.lastElement)&&this.element(b)},onclick:function(b){b.name in this.submitted?this.element(b):b.parentNode.name in this.submitted&&this.element(b.parentNode)},highlight:function(c,a,d){"radio"===c.type?this.findByName(c.name).addClass(a).removeClass(d):b(c).addClass(a).removeClass(d)},unhighlight:function(c,a,d){"radio"===c.type?this.findByName(c.name).removeClass(a).addClass(d):b(c).removeClass(a).addClass(d)}},setDefaults:function(c){b.extend(b.validator.defaults,c)},messages:{required:"This field is required.",
remote:"Please fix this field.",email:"Please enter a valid email address.",url:"Please enter a valid URL.",date:"Please enter a valid date.",dateISO:"Please enter a valid date (ISO).",number:"Please enter a valid number.",digits:"Please enter only digits.",creditcard:"Please enter a valid credit card number.",equalTo:"Please enter the same value again.",accept:"Please enter a value with a valid extension.",maxlength:b.validator.format("Please enter no more than {0} characters."),minlength:b.validator.format("Please enter at least {0} characters."),
rangelength:b.validator.format("Please enter a value between {0} and {1} characters long."),range:b.validator.format("Please enter a value between {0} and {1}."),max:b.validator.format("Please enter a value less than or equal to {0}."),min:b.validator.format("Please enter a value greater than or equal to {0}.")},autoCreateRanges:!1,prototype:{init:function(){function c(a){var d=b.data(this[0].form,"validator"),c="on"+a.type.replace(/^validate/,"");d.settings[c]&&d.settings[c].call(d,this[0],a)}this.labelContainer=
b(this.settings.errorLabelContainer);this.errorContext=this.labelContainer.length&&this.labelContainer||b(this.currentForm);this.containers=b(this.settings.errorContainer).add(this.settings.errorLabelContainer);this.submitted={};this.valueCache={};this.pendingRequest=0;this.pending={};this.invalid={};this.reset();var a=this.groups={};b.each(this.settings.groups,function(d,c){b.each(c.split(/\s/),function(b,c){a[c]=d})});var d=this.settings.rules;b.each(d,function(a,c){d[a]=b.validator.normalizeRule(c)});
b(this.currentForm).validateDelegate("[type='text'], [type='password'], [type='file'], select, textarea, [type='number'], [type='search'] ,[type='tel'], [type='url'], [type='email'], [type='datetime'], [type='date'], [type='month'], [type='week'], [type='time'], [type='datetime-local'], [type='range'], [type='color'] ","focusin focusout keyup",c).validateDelegate("[type='radio'], [type='checkbox'], select, option","click",c);this.settings.invalidHandler&&b(this.currentForm).bind("invalid-form.validate",
this.settings.invalidHandler)},form:function(){this.checkForm();b.extend(this.submitted,this.errorMap);this.invalid=b.extend({},this.errorMap);this.valid()||b(this.currentForm).triggerHandler("invalid-form",[this]);this.showErrors();return this.valid()},checkForm:function(){this.prepareForm();for(var b=0,a=this.currentElements=this.elements();a[b];b++)this.check(a[b]);return this.valid()},element:function(c){this.lastElement=c=this.validationTargetFor(this.clean(c));this.prepareElement(c);this.currentElements=
b(c);var a=this.check(c);a?delete this.invalid[c.name]:this.invalid[c.name]=!0;this.numberOfInvalids()||(this.toHide=this.toHide.add(this.containers));this.showErrors();return a},showErrors:function(c){if(c){b.extend(this.errorMap,c);this.errorList=[];for(var a in c)this.errorList.push({message:c[a],element:this.findByName(a)[0]});this.successList=b.grep(this.successList,function(a){return!(a.name in c)})}this.settings.showErrors?this.settings.showErrors.call(this,this.errorMap,this.errorList):this.defaultShowErrors()},
resetForm:function(){b.fn.resetForm&&b(this.currentForm).resetForm();this.submitted={};this.lastElement=null;this.prepareForm();this.hideErrors();this.elements().removeClass(this.settings.errorClass)},numberOfInvalids:function(){return this.objectLength(this.invalid)},objectLength:function(b){var a=0,d;for(d in b)a++;return a},hideErrors:function(){this.addWrapper(this.toHide).hide()},valid:function(){return 0==this.size()},size:function(){return this.errorList.length},focusInvalid:function(){if(this.settings.focusInvalid)try{b(this.findLastActive()||
this.errorList.length&&this.errorList[0].element||[]).filter(":visible").focus().trigger("focusin")}catch(c){}},findLastActive:function(){var c=this.lastActive;return c&&1==b.grep(this.errorList,function(a){return a.element.name==c.name}).length&&c},elements:function(){var c=this,a={};return b(this.currentForm).find("input, select, textarea").not(":submit, :reset, :image, [disabled]").not(this.settings.ignore).filter(function(){!this.name&&c.settings.debug&&window.console&&console.error("%o has no name assigned",
this);return this.name in a||!c.objectLength(b(this).rules())?!1:a[this.name]=!0})},clean:function(c){return b(c)[0]},errors:function(){return b(this.settings.errorElement+"."+this.settings.errorClass,this.errorContext)},reset:function(){this.successList=[];this.errorList=[];this.errorMap={};this.toShow=b([]);this.toHide=b([]);this.currentElements=b([])},prepareForm:function(){this.reset();this.toHide=this.errors().add(this.containers)},prepareElement:function(b){this.reset();this.toHide=this.errorsFor(b)},
check:function(c){c=this.validationTargetFor(this.clean(c));var a=b(c).rules(),d=!1,g;for(g in a){var e={method:g,parameters:a[g]};try{var h=b.validator.methods[g].call(this,c.value.replace(/\r/g,""),c,e.parameters);if("dependency-mismatch"==h)d=!0;else{d=!1;if("pending"==h){this.toHide=this.toHide.not(this.errorsFor(c));return}if(!h)return this.formatAndAdd(c,e),!1}}catch(f){throw this.settings.debug&&window.console&&console.log("exception occured when checking element "+c.id+", check the '"+e.method+
"' method",f),f;}}if(!d)return this.objectLength(a)&&this.successList.push(c),!0},customMetaMessage:function(c,a){if(b.metadata){var d=this.settings.meta?b(c).metadata()[this.settings.meta]:b(c).metadata();return d&&d.messages&&d.messages[a]}},customMessage:function(b,a){var d=this.settings.messages[b];return d&&(d.constructor==String?d:d[a])},findDefined:function(){for(var b=0;b<arguments.length;b++)if(void 0!==arguments[b])return arguments[b]},defaultMessage:function(c,a){return this.findDefined(this.customMessage(c.name,
a),this.customMetaMessage(c,a),!this.settings.ignoreTitle&&c.title||void 0,b.validator.messages[a],"<strong>Warning: No message defined for "+c.name+"</strong>")},formatAndAdd:function(b,a){var d=this.defaultMessage(b,a.method),g=/\$?\{(\d+)\}/g;"function"==typeof d?d=d.call(this,a.parameters,b):g.test(d)&&(d=jQuery.format(d.replace(g,"{$1}"),a.parameters));this.errorList.push({message:d,element:b});this.errorMap[b.name]=d;this.submitted[b.name]=d},addWrapper:function(b){this.settings.wrapper&&(b=
b.add(b.parent(this.settings.wrapper)));return b},defaultShowErrors:function(){for(var b=0;this.errorList[b];b++){var a=this.errorList[b];this.settings.highlight&&this.settings.highlight.call(this,a.element,this.settings.errorClass,this.settings.validClass);this.showLabel(a.element,a.message)}this.errorList.length&&(this.toShow=this.toShow.add(this.containers));if(this.settings.success)for(b=0;this.successList[b];b++)this.showLabel(this.successList[b]);if(this.settings.unhighlight)for(b=0,a=this.validElements();a[b];b++)this.settings.unhighlight.call(this,
a[b],this.settings.errorClass,this.settings.validClass);this.toHide=this.toHide.not(this.toShow);this.hideErrors();this.addWrapper(this.toShow).show()},validElements:function(){return this.currentElements.not(this.invalidElements())},invalidElements:function(){return b(this.errorList).map(function(){return this.element})},showLabel:function(c,a){var d=this.errorsFor(c);d.length?(d.removeClass(this.settings.validClass).addClass(this.settings.errorClass),d.attr("generated")&&d.html(a)):(d=b("<"+this.settings.errorElement+
"/>").attr({"for":this.idOrName(c),generated:!0}).addClass(this.settings.errorClass).html(a||""),this.settings.wrapper&&(d=d.hide().show().wrap("<"+this.settings.wrapper+"/>").parent()),this.labelContainer.append(d).length||(this.settings.errorPlacement?this.settings.errorPlacement(d,b(c)):d.insertAfter(c)));!a&&this.settings.success&&(d.text(""),"string"==typeof this.settings.success?d.addClass(this.settings.success):this.settings.success(d));this.toShow=this.toShow.add(d)},errorsFor:function(c){var a=
this.idOrName(c);return this.errors().filter(function(){return b(this).attr("for")==a})},idOrName:function(b){return this.groups[b.name]||(this.checkable(b)?b.name:b.id||b.name)},validationTargetFor:function(b){this.checkable(b)&&(b=this.findByName(b.name).not(this.settings.ignore)[0]);return b},checkable:function(b){return/radio|checkbox/i.test(b.type)},findByName:function(c){var a=this.currentForm;return b(document.getElementsByName(c)).map(function(b,g){return g.form==a&&g.name==c&&g||null})},
getLength:function(c,a){switch(a.nodeName.toLowerCase()){case "select":return b("option:selected",a).length;case "input":if(this.checkable(a))return this.findByName(a.name).filter(":checked").length}return c.length},depend:function(b,a){return this.dependTypes[typeof b]?this.dependTypes[typeof b](b,a):!0},dependTypes:{"boolean":function(b){return b},string:function(c,a){return!!b(c,a.form).length},"function":function(b,a){return b(a)}},optional:function(c){return!b.validator.methods.required.call(this,
b.trim(c.value),c)&&"dependency-mismatch"},startRequest:function(b){this.pending[b.name]||(this.pendingRequest++,this.pending[b.name]=!0)},stopRequest:function(c,a){this.pendingRequest--;0>this.pendingRequest&&(this.pendingRequest=0);delete this.pending[c.name];a&&0==this.pendingRequest&&this.formSubmitted&&this.form()?(b(this.currentForm).submit(),this.formSubmitted=!1):!a&&0==this.pendingRequest&&this.formSubmitted&&(b(this.currentForm).triggerHandler("invalid-form",[this]),this.formSubmitted=!1)},
previousValue:function(c){return b.data(c,"previousValue")||b.data(c,"previousValue",{old:null,valid:!0,message:this.defaultMessage(c,"remote")})}},classRuleSettings:{required:{required:!0},email:{email:!0},url:{url:!0},date:{date:!0},dateISO:{dateISO:!0},dateDE:{dateDE:!0},number:{number:!0},numberDE:{numberDE:!0},digits:{digits:!0},creditcard:{creditcard:!0}},addClassRules:function(c,a){c.constructor==String?this.classRuleSettings[c]=a:b.extend(this.classRuleSettings,c)},classRules:function(c){var a=
{};(c=b(c).attr("class"))&&b.each(c.split(" "),function(){this in b.validator.classRuleSettings&&b.extend(a,b.validator.classRuleSettings[this])});return a},attributeRules:function(c){var a={};c=b(c);for(var d in b.validator.methods){var g;(g="required"===d&&"function"===typeof b.fn.prop?c.prop(d):c.attr(d))?a[d]=g:c[0].getAttribute("type")===d&&(a[d]=!0)}a.maxlength&&/-1|2147483647|524288/.test(a.maxlength)&&delete a.maxlength;return a},metadataRules:function(c){if(!b.metadata)return{};var a=b.data(c.form,
"validator").settings.meta;return a?b(c).metadata()[a]:b(c).metadata()},staticRules:function(c){var a={},d=b.data(c.form,"validator");d.settings.rules&&(a=b.validator.normalizeRule(d.settings.rules[c.name])||{});return a},normalizeRules:function(c,a){b.each(c,function(d,g){if(!1===g)delete c[d];else if(g.param||g.depends){var e=!0;switch(typeof g.depends){case "string":e=!!b(g.depends,a.form).length;break;case "function":e=g.depends.call(a,a)}e?c[d]=void 0!==g.param?g.param:!0:delete c[d]}});b.each(c,
function(d,g){c[d]=b.isFunction(g)?g(a):g});b.each(["minlength","maxlength","min","max"],function(){c[this]&&(c[this]=Number(c[this]))});b.each(["rangelength","range"],function(){c[this]&&(c[this]=[Number(c[this][0]),Number(c[this][1])])});b.validator.autoCreateRanges&&(c.min&&c.max&&(c.range=[c.min,c.max],delete c.min,delete c.max),c.minlength&&c.maxlength&&(c.rangelength=[c.minlength,c.maxlength],delete c.minlength,delete c.maxlength));c.messages&&delete c.messages;return c},normalizeRule:function(c){if("string"==
typeof c){var a={};b.each(c.split(/\s/),function(){a[this]=!0});c=a}return c},addMethod:function(c,a,d){b.validator.methods[c]=a;b.validator.messages[c]=void 0!=d?d:b.validator.messages[c];3>a.length&&b.validator.addClassRules(c,b.validator.normalizeRule(c))},methods:{required:function(c,a,d){if(!this.depend(d,a))return"dependency-mismatch";switch(a.nodeName.toLowerCase()){case "select":return(c=b(a).val())&&0<c.length;case "input":if(this.checkable(a))return 0<this.getLength(c,a);default:return 0<
b.trim(c).length}},remote:function(c,a,d){if(this.optional(a))return"dependency-mismatch";var g=this.previousValue(a);this.settings.messages[a.name]||(this.settings.messages[a.name]={});g.originalMessage=this.settings.messages[a.name].remote;this.settings.messages[a.name].remote=g.message;d="string"==typeof d&&{url:d}||d;if(this.pending[a.name])return"pending";if(g.old===c)return g.valid;g.old=c;var e=this;this.startRequest(a);var h={};h[a.name]=c;b.ajax(b.extend(!0,{url:d,mode:"abort",port:"validate"+
a.name,dataType:"json",data:h,success:function(d){e.settings.messages[a.name].remote=g.originalMessage;var h=!0===d;if(h){var k=e.formSubmitted;e.prepareElement(a);e.formSubmitted=k;e.successList.push(a);e.showErrors()}else k={},d=d||e.defaultMessage(a,"remote"),k[a.name]=g.message=b.isFunction(d)?d(c):d,e.showErrors(k);g.valid=h;e.stopRequest(a,h)}},d));return"pending"},minlength:function(c,a,d){return this.optional(a)||this.getLength(b.trim(c),a)>=d},maxlength:function(c,a,d){return this.optional(a)||
this.getLength(b.trim(c),a)<=d},rangelength:function(c,a,d){c=this.getLength(b.trim(c),a);return this.optional(a)||c>=d[0]&&c<=d[1]},min:function(b,a,d){return this.optional(a)||b>=d},max:function(b,a,d){return this.optional(a)||b<=d},range:function(b,a,d){return this.optional(a)||b>=d[0]&&b<=d[1]},email:function(b,a){return this.optional(a)||/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))$/i.test(b)},
url:function(b,a){return this.optional(a)||/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i.test(b)},
date:function(b,a){return this.optional(a)||!/Invalid|NaN/.test(new Date(b))},dateISO:function(b,a){return this.optional(a)||/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(b)},number:function(b,a){return this.optional(a)||/^-?(?:\d+|\d{1,3}(?:,\d{3})+)(?:\.\d+)?$/.test(b)},digits:function(b,a){return this.optional(a)||/^\d+$/.test(b)},creditcard:function(b,a){if(this.optional(a))return"dependency-mismatch";if(/[^0-9 -]+/.test(b))return!1;var d=0,g=0,e=!1;b=b.replace(/\D/g,"");for(var h=b.length-1;0<=h;h--)g=
b.charAt(h),g=parseInt(g,10),e&&9<(g*=2)&&(g-=9),d+=g,e=!e;return 0==d%10},accept:function(b,a,d){d="string"==typeof d?d.replace(/,/g,"|"):"png|jpe?g|gif";return this.optional(a)||b.match(RegExp(".("+d+")$","i"))},equalTo:function(c,a,d){d=b(d).unbind(".validate-equalTo").bind("blur.validate-equalTo",function(){b(a).valid()});return c==d.val()}}});b.format=b.validator.format})(jQuery);
(function(b){var c={};if(b.ajaxPrefilter)b.ajaxPrefilter(function(a,b,e){b=a.port;"abort"==a.mode&&(c[b]&&c[b].abort(),c[b]=e)});else{var a=b.ajax;b.ajax=function(d){var g=("port"in d?d:b.ajaxSettings).port;return"abort"==("mode"in d?d:b.ajaxSettings).mode?(c[g]&&c[g].abort(),c[g]=a.apply(this,arguments)):a.apply(this,arguments)}}})(jQuery);
(function(b){!jQuery.event.special.focusin&&!jQuery.event.special.focusout&&document.addEventListener&&b.each({focus:"focusin",blur:"focusout"},function(c,a){function d(d){d=b.event.fix(d);d.type=a;return b.event.handle.call(this,d)}b.event.special[a]={setup:function(){this.addEventListener(c,d,!0)},teardown:function(){this.removeEventListener(c,d,!0)},handler:function(d){arguments[0]=b.event.fix(d);arguments[0].type=a;return b.event.handle.apply(this,arguments)}}});b.extend(b.fn,{validateDelegate:function(c,
a,d){return this.bind(a,function(a){var e=b(a.target);if(e.is(c))return d.apply(e,arguments)})}})})(jQuery);
(function(b){function c(){if(b.fn.ajaxSubmit.debug){var a="[jquery.form] "+Array.prototype.join.call(arguments,"");window.console&&window.console.log?window.console.log(a):window.opera&&window.opera.postError&&window.opera.postError(a)}}b.fn.ajaxSubmit=function(a){function d(d){for(var e=new FormData,g=0;g<d.length;g++)"file"!=d[g].type&&e.append(d[g].name,d[g].value);f.find("input:file:enabled").each(function(){var a=b(this).attr("name"),d=this.files;if(a)for(var g=0;g<d.length;g++)e.append(a,d[g])});
if(a.extraData)for(var c in a.extraData)e.append(c,a.extraData[c]);a.data=null;d=b.extend(!0,{},b.ajaxSettings,a,{contentType:!1,processData:!1,cache:!1,type:"POST"});d.context=d.context||d;d.data=null;var h=d.beforeSend;d.beforeSend=function(b,d){d.data=e;b.upload&&(b.upload.onprogress=function(a){d.progress(a.position,a.total)});h&&h.call(d,b,a)};b.ajax(d)}function g(d){function g(){function a(){try{var b=(u.contentWindow?u.contentWindow.document:u.contentDocument?u.contentDocument:u.document).readyState;
c("state = "+b);"uninitialized"==b.toLowerCase()&&setTimeout(a,50)}catch(d){c("Server abort: ",d," (",d.name,")"),h(2),z&&clearTimeout(z),z=void 0}}var d=f.attr("target"),l=f.attr("action");k.setAttribute("target",x);e||k.setAttribute("method","POST");l!=m.url&&k.setAttribute("action",m.url);m.skipEncodingOverride||e&&!/post/i.test(e)||f.attr({encoding:"multipart/form-data",enctype:"multipart/form-data"});m.timeout&&(z=setTimeout(function(){B=!0;h(1)},m.timeout));var n=[];try{if(m.extraData)for(var r in m.extraData)n.push(b('<input type="hidden" name="'+
r+'">').attr("value",m.extraData[r]).appendTo(k)[0]);m.iframeTarget||(w.appendTo("body"),u.attachEvent?u.attachEvent("onload",h):u.addEventListener("load",h,!1));setTimeout(a,15);k.submit()}finally{k.setAttribute("action",l),d?k.setAttribute("target",d):f.removeAttr("target"),b(n).remove()}}function h(a){if(!p.aborted&&!V){try{v=u.contentWindow?u.contentWindow.document:u.contentDocument?u.contentDocument:u.document}catch(d){c("cannot access response document: ",d),a=2}if(1===a&&p)p.abort("timeout");
else if(2==a&&p)p.abort("server abort");else if(v&&v.location.href!=m.iframeSrc||B){u.detachEvent?u.detachEvent("onload",h):u.removeEventListener("load",h,!1);a="success";var e;try{if(B)throw"timeout";var g="xml"==m.dataType||v.XMLDocument||b.isXMLDoc(v);c("isXml="+g);if(!g&&window.opera&&(null==v.body||""==v.body.innerHTML)&&--F){c("requeing onLoad callback, DOM not available");setTimeout(h,250);return}var f=v.body?v.body:v.documentElement;p.responseText=f?f.innerHTML:null;p.responseXML=v.XMLDocument?
v.XMLDocument:v;g&&(m.dataType="xml");p.getResponseHeader=function(a){return{"content-type":m.dataType}[a]};f&&(p.status=Number(f.getAttribute("status"))||p.status,p.statusText=f.getAttribute("statusText")||p.statusText);var k=(m.dataType||"").toLowerCase(),l=/(json|script|text)/.test(k);if(l||m.textarea){var n=v.getElementsByTagName("textarea")[0];if(n)p.responseText=n.value,p.status=Number(n.getAttribute("status"))||p.status,p.statusText=n.getAttribute("statusText")||p.statusText;else if(l){var x=
v.getElementsByTagName("pre")[0],y=v.getElementsByTagName("body")[0];x?p.responseText=x.textContent?x.textContent:x.innerText:y&&(p.responseText=y.textContent?y.textContent:y.innerText)}}else"xml"!=k||p.responseXML||null==p.responseText||(p.responseXML=ba(p.responseText));try{C=na(p,k,m)}catch(L){a="parsererror",p.error=e=L||a}}catch(A){c("error caught: ",A),a="error",p.error=e=A||a}p.aborted&&(c("upload aborted"),a=null);p.status&&(a=200<=p.status&&300>p.status||304===p.status?"success":"error");
"success"===a?(m.success&&m.success.call(m.context,C,"success",p),r&&b.event.trigger("ajaxSuccess",[p,m])):a&&(void 0==e&&(e=p.statusText),m.error&&m.error.call(m.context,p,a,e),r&&b.event.trigger("ajaxError",[p,m,e]));r&&b.event.trigger("ajaxComplete",[p,m]);r&&!--b.active&&b.event.trigger("ajaxStop");m.complete&&m.complete.call(m.context,p,a);V=!0;m.timeout&&clearTimeout(z);setTimeout(function(){m.iframeTarget||w.remove();p.responseXML=null},100)}}}var k=f[0],l,n,m,r,x,w,u,p,B,z;l=!!b.fn.prop;if(d)if(l)for(n=
0;n<d.length;n++)l=b(k[d[n].name]),l.prop("disabled",!1);else for(n=0;n<d.length;n++)l=b(k[d[n].name]),l.removeAttr("disabled");if(b(":input[name=submit],:input[id=submit]",k).length)alert('Error: Form elements must not have name or id of "submit".');else if(m=b.extend(!0,{},b.ajaxSettings,a),m.context=m.context||m,x="jqFormIO"+(new Date).getTime(),m.iframeTarget?(w=b(m.iframeTarget),l=w.attr("name"),null==l?w.attr("name",x):x=l):(w=b('<iframe name="'+x+'" src="'+m.iframeSrc+'" />'),w.css({position:"absolute",
top:"-1000px",left:"-1000px"})),u=w[0],p={aborted:0,responseText:null,responseXML:null,status:0,statusText:"n/a",getAllResponseHeaders:function(){},getResponseHeader:function(){},setRequestHeader:function(){},abort:function(a){var d="timeout"===a?"timeout":"aborted";c("aborting upload... "+d);this.aborted=1;w.attr("src",m.iframeSrc);p.error=d;m.error&&m.error.call(m.context,p,d,a);r&&b.event.trigger("ajaxError",[p,m,d]);m.complete&&m.complete.call(m.context,p,d)}},(r=m.global)&&!b.active++&&b.event.trigger("ajaxStart"),
r&&b.event.trigger("ajaxSend",[p,m]),m.beforeSend&&!1===m.beforeSend.call(m.context,p,m))m.global&&b.active--;else if(!p.aborted){(d=k.clk)&&(l=d.name)&&!d.disabled&&(m.extraData=m.extraData||{},m.extraData[l]=d.value,"image"==d.type&&(m.extraData[l+".x"]=k.clk_x,m.extraData[l+".y"]=k.clk_y));d=b("meta[name=csrf-token]").attr("content");(l=b("meta[name=csrf-param]").attr("content"))&&d&&(m.extraData=m.extraData||{},m.extraData[l]=d);m.forceSync?g():setTimeout(g,10);var C,v,F=50,V,ba=b.parseXML||function(a,
b){window.ActiveXObject?(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a)):b=(new DOMParser).parseFromString(a,"text/xml");return b&&b.documentElement&&"parsererror"!=b.documentElement.nodeName?b:null},ca=b.parseJSON||function(a){return window.eval("("+a+")")},na=function(a,d,e){var g=a.getResponseHeader("content-type")||"",c="xml"===d||!d&&0<=g.indexOf("xml");a=c?a.responseXML:a.responseText;c&&"parsererror"===a.documentElement.nodeName&&b.error&&b.error("parsererror");e&&e.dataFilter&&
(a=e.dataFilter(a,d));"string"===typeof a&&("json"===d||!d&&0<=g.indexOf("json")?a=ca(a):("script"===d||!d&&0<=g.indexOf("javascript"))&&b.globalEval(a));return a}}}if(!this.length)return c("ajaxSubmit: skipping submit process - no element selected"),this;var e,h,f=this;"function"==typeof a&&(a={success:a});e=this.attr("method");h=this.attr("action");(h=(h="string"===typeof h?b.trim(h):"")||window.location.href||"")&&(h=(h.match(/^([^#]+)/)||[])[1]);a=b.extend(!0,{url:h,success:b.ajaxSettings.success,
type:e||"GET",iframeSrc:/^https/i.test(window.location.href||"")?"javascript:false":"about:blank"},a);h={};this.trigger("form-pre-serialize",[this,a,h]);if(h.veto)return c("ajaxSubmit: submit vetoed via form-pre-serialize trigger"),this;if(a.beforeSerialize&&!1===a.beforeSerialize(this,a))return c("ajaxSubmit: submit aborted via beforeSerialize callback"),this;var l=a.traditional;void 0===l&&(l=b.ajaxSettings.traditional);var k,n=this.formToArray(a.semantic);a.data&&(a.extraData=a.data,k=b.param(a.data,
l));if(a.beforeSubmit&&!1===a.beforeSubmit(n,this,a))return c("ajaxSubmit: submit aborted via beforeSubmit callback"),this;this.trigger("form-submit-validate",[n,this,a,h]);if(h.veto)return c("ajaxSubmit: submit vetoed via form-submit-validate trigger"),this;h=b.param(n,l);k&&(h=h?h+"&"+k:k);"GET"==a.type.toUpperCase()?(a.url+=(0<=a.url.indexOf("?")?"&":"?")+h,a.data=null):a.data=h;var r=[];a.resetForm&&r.push(function(){f.resetForm()});a.clearForm&&r.push(function(){f.clearForm(a.includeHidden)});
if(!a.dataType&&a.target){var x=a.success||function(){};r.push(function(d){var e=a.replaceTarget?"replaceWith":"html";b(a.target)[e](d).each(x,arguments)})}else a.success&&r.push(a.success);a.success=function(b,d,e){for(var g=a.context||a,c=0,h=r.length;c<h;c++)r[c].apply(g,[b,d,e||f,f])};l=b("input:file:enabled[value]",this);k=0<l.length;h="multipart/form-data"==f.attr("enctype")||"multipart/form-data"==f.attr("encoding");l=!!(k&&l.get(0).files&&window.FormData);c("fileAPI :"+l);!1!==a.iframe&&(a.iframe||
(k||h)&&!l)?a.closeKeepAlive?b.get(a.closeKeepAlive,function(){g(n)}):g(n):(k||h)&&l?(a.progress=a.progress||b.noop,d(n)):b.ajax(a);this.trigger("form-submit-notify",[this,a]);return this};b.fn.ajaxForm=function(a){if(0===this.length){var d=this.selector,g=this.context;if(!b.isReady&&d)return c("DOM not ready, queuing ajaxForm"),b(function(){b(d,g).ajaxForm(a)}),this;c("terminating; zero elements found by selector"+(b.isReady?"":" (DOM not ready)"));return this}return this.ajaxFormUnbind().bind("submit.form-plugin",
function(d){d.isDefaultPrevented()||(d.preventDefault(),b(this).ajaxSubmit(a))}).bind("click.form-plugin",function(a){var d=a.target,g=b(d);if(!g.is(":submit,input:image")){d=g.closest(":submit");if(0==d.length)return;d=d[0]}var c=this;c.clk=d;"image"==d.type&&(void 0!=a.offsetX?(c.clk_x=a.offsetX,c.clk_y=a.offsetY):"function"==typeof b.fn.offset?(g=g.offset(),c.clk_x=a.pageX-g.left,c.clk_y=a.pageY-g.top):(c.clk_x=a.pageX-d.offsetLeft,c.clk_y=a.pageY-d.offsetTop));setTimeout(function(){c.clk=c.clk_x=
c.clk_y=null},100)})};b.fn.ajaxFormUnbind=function(){return this.unbind("submit.form-plugin click.form-plugin")};b.fn.formToArray=function(a){var d=[];if(0===this.length)return d;var g=this[0],e=a?g.getElementsByTagName("*"):g.elements;if(!e)return d;var c,f,l,k,n,r;c=0;for(n=e.length;c<n;c++)if(f=e[c],l=f.name)if(a&&g.clk&&"image"==f.type)f.disabled||g.clk!=f||(d.push({name:l,value:b(f).val(),type:f.type}),d.push({name:l+".x",value:g.clk_x},{name:l+".y",value:g.clk_y}));else if((k=b.fieldValue(f,
!0))&&k.constructor==Array)for(f=0,r=k.length;f<r;f++)d.push({name:l,value:k[f]});else null!==k&&"undefined"!=typeof k&&d.push({name:l,value:k,type:f.type});!a&&g.clk&&(a=b(g.clk),e=a[0],(l=e.name)&&!e.disabled&&"image"==e.type&&(d.push({name:l,value:a.val()}),d.push({name:l+".x",value:g.clk_x},{name:l+".y",value:g.clk_y})));return d};b.fn.formSerialize=function(a){return b.param(this.formToArray(a))};b.fn.fieldSerialize=function(a){var d=[];this.each(function(){var g=this.name;if(g){var e=b.fieldValue(this,
a);if(e&&e.constructor==Array)for(var c=0,f=e.length;c<f;c++)d.push({name:g,value:e[c]});else null!==e&&"undefined"!=typeof e&&d.push({name:this.name,value:e})}});return b.param(d)};b.fn.fieldValue=function(a){for(var d=[],g=0,e=this.length;g<e;g++){var c=b.fieldValue(this[g],a);null===c||"undefined"==typeof c||c.constructor==Array&&!c.length||(c.constructor==Array?b.merge(d,c):d.push(c))}return d};b.fieldValue=function(a,d){var c=a.name,e=a.type,h=a.tagName.toLowerCase();void 0===d&&(d=!0);if(d&&
(!c||a.disabled||"reset"==e||"button"==e||("checkbox"==e||"radio"==e)&&!a.checked||("submit"==e||"image"==e)&&a.form&&a.form.clk!=a||"select"==h&&-1==a.selectedIndex))return null;if("select"==h){var f=a.selectedIndex;if(0>f)return null;for(var c=[],h=a.options,l=(e="select-one"==e)?f+1:h.length,f=e?f:0;f<l;f++){var k=h[f];if(k.selected){var n=k.value;n||(n=k.attributes&&k.attributes.value&&!k.attributes.value.specified?k.text:k.value);if(e)return n;c.push(n)}}return c}return b(a).val()};b.fn.clearForm=
function(a){return this.each(function(){b("input,select,textarea",this).clearFields(a)})};b.fn.clearFields=b.fn.clearInputs=function(a){var b=/^(?:color|date|datetime|email|month|number|password|range|search|tel|text|time|url|week)$/i;return this.each(function(){var c=this.type,e=this.tagName.toLowerCase();b.test(c)||"textarea"==e||a&&/hidden/.test(c)?this.value="":"checkbox"==c||"radio"==c?this.checked=!1:"select"==e&&(this.selectedIndex=-1)})};b.fn.resetForm=function(){return this.each(function(){("function"==
typeof this.reset||"object"==typeof this.reset&&!this.reset.nodeType)&&this.reset()})};b.fn.enable=function(a){void 0===a&&(a=!0);return this.each(function(){this.disabled=!a})};b.fn.selected=function(a){void 0===a&&(a=!0);return this.each(function(){var d=this.type;"checkbox"==d||"radio"==d?this.checked=a:"option"==this.tagName.toLowerCase()&&(d=b(this).parent("select"),a&&d[0]&&"select-one"==d[0].type&&d.find("option").selected(!1),this.selected=a)})};b.fn.ajaxSubmit.debug=!1})(jQuery);
$(function(){$("#contactform").validate({errorElement:"label",wrapper:"td",errorPlacement:function(b,c){b.insertBefore(c.parent().parent());b.wrap("<tr class='error'></tr>");$("<td></td>").insertBefore(b)},rules:{name:{required:!0,minlength:2},email:{required:!0,email:!0},message:{required:!0,minlength:10}},messages:{name:{required:"Please enter your name.",minlength:jQuery.format("At least {0} characters required.")},email:{required:"Please enter your email.",email:"Please enter a valid email."},
message:{required:"Please enter a message.",minlength:jQuery.format("At least {0} characters required.")}},submitHandler:function(b){$("#send").attr("value","Sending...");$(b).ajaxSubmit({success:function(c,a,d,g){$(b).slideUp("slow");$("#response").html(c).hide().slideDown("slow")}});return!1}})});
(function(b){b.fn.tcycle=function(){return this.each(function(){function c(){var e=a==f-1?0:a+1,c=d.width(),l=b(g[a]),e=b(g[e]);h?(l.fadeOut(k),e.fadeIn(k,x)):(l.animate({right:-c},k,function(){l.hide()}),e.css({right:c,display:"block"}).animate({right:0},k,x));a=a==f-1?0:a+1}var a=0,d=b(this),g=d.children(),e=b.extend({speed:500,timeout:4E3},d.data()),h="scroll"!=e.fx,f=g.length,l=d.width(),k=e.speed,n=e.timeout,r={overflow:"hidden"},x=function(){setTimeout(c,n)},e=b.extend({position:"absolute",
top:0},h?{right:0}:{right:l},e.scss);"static"==d.css("position")&&(r.position="relative");d.prepend(b(g[0]).clone().css("visibility","hidden")).css(r);g.css(e);h?g.hide().eq(0).show():g.eq(0).css("right",0);setTimeout(c,n)})};b(function(){b(".tcycle").tcycle()})})(jQuery);
!function(b){function c(a){return(a||"").toLowerCase()}b.fn.cycle=function(a){var d;return 0!==this.length||b.isReady?this.each(function(){var d,e,h,f,l=b(this),k=b.fn.cycle.log;if(!l.data("cycle.opts")){(!1===l.data("cycle-log")||a&&!1===a.log||e&&!1===e.log)&&(k=b.noop);k("--c2 init--");d=l.data();for(var n in d)d.hasOwnProperty(n)&&/^cycle[A-Z]+/.test(n)&&(f=d[n],h=n.match(/^cycle(.*)/)[1].replace(/^[A-Z]/,c),k(h+":",f,"("+typeof f+")"),d[h]=f);e=b.extend({},b.fn.cycle.defaults,d,a||{});e.timeoutId=
0;e.paused=e.paused||!1;e.container=l;e._maxZ=e.maxZ;e.API=b.extend({_container:l},b.fn.cycle.API);e.API.log=k;e.API.trigger=function(a,b){return e.container.trigger(a,b),e.API};l.data("cycle.opts",e);l.data("cycle.API",e.API);e.API.trigger("cycle-bootstrap",[e,e.API]);e.API.addInitialSlides();e.API.preInitSlideshow();e.slides.length&&e.API.initSlideshow()}}):(d={s:this.selector,c:this.context},b.fn.cycle.log("requeuing slideshow (dom not ready)"),b(function(){b(d.s,d.c).cycle(a)}),this)};b.fn.cycle.API=
{opts:function(){return this._container.data("cycle.opts")},addInitialSlides:function(){var a=this.opts(),d=a.slides;a.slideCount=0;a.slides=b();d=d.jquery?d:a.container.find(d);a.random&&d.sort(function(){return Math.random()-.5});a.API.add(d)},preInitSlideshow:function(){var a=this.opts();a.API.trigger("cycle-pre-initialize",[a]);var d=b.fn.cycle.transitions[a.fx];d&&b.isFunction(d.preInit)&&d.preInit(a);a._preInitialized=!0},postInitSlideshow:function(){var a=this.opts();a.API.trigger("cycle-post-initialize",
[a]);var d=b.fn.cycle.transitions[a.fx];d&&b.isFunction(d.postInit)&&d.postInit(a)},initSlideshow:function(){var a,d=this.opts(),c=d.container;d.API.calcFirstSlide();"static"==d.container.css("position")&&d.container.css("position","relative");b(d.slides[d.currSlide]).css({opacity:1,display:"block",visibility:"visible"});d.API.stackSlides(d.slides[d.currSlide],d.slides[d.nextSlide],!d.reverse);d.pauseOnHover&&(!0!==d.pauseOnHover&&(c=b(d.pauseOnHover)),c.hover(function(){d.API.pause(!0)},function(){d.API.resume(!0)}));
d.timeout&&(a=d.API.getSlideOpts(d.currSlide),d.API.queueTransition(a,a.timeout+d.delay));d._initialized=!0;d.API.updateView(!0);d.API.trigger("cycle-initialized",[d]);d.API.postInitSlideshow()},pause:function(a){var d=this.opts(),c=d.API.getSlideOpts(),e=d.hoverPaused||d.paused;a?d.hoverPaused=!0:d.paused=!0;e||(d.container.addClass("cycle-paused"),d.API.trigger("cycle-paused",[d]).log("cycle-paused"),c.timeout&&(clearTimeout(d.timeoutId),d.timeoutId=0,d._remainingTimeout-=b.now()-d._lastQueue,(0>
d._remainingTimeout||isNaN(d._remainingTimeout))&&(d._remainingTimeout=void 0)))},resume:function(a){var b=this.opts(),c=!b.hoverPaused&&!b.paused;a?b.hoverPaused=!1:b.paused=!1;c||(b.container.removeClass("cycle-paused"),0===b.slides.filter(":animated").length&&b.API.queueTransition(b.API.getSlideOpts(),b._remainingTimeout),b.API.trigger("cycle-resumed",[b,b._remainingTimeout]).log("cycle-resumed"))},add:function(a,d){var c,e=this.opts(),h=e.slideCount,f=!1;"string"==b.type(a)&&(a=b.trim(a));b(a).each(function(){var a,
c=b(this);d?e.container.prepend(c):e.container.append(c);e.slideCount++;a=e.API.buildSlideOpts(c);e.slides=d?b(c).add(e.slides):e.slides.add(c);e.API.initSlide(a,c,--e._maxZ);c.data("cycle.opts",a);e.API.trigger("cycle-slide-added",[e,a,c])});e.API.updateView(!0);(f=e._preInitialized&&2>h&&1<=e.slideCount)&&(e._initialized?e.timeout&&(c=e.slides.length,e.nextSlide=e.reverse?c-1:1,e.timeoutId||e.API.queueTransition(e)):e.API.initSlideshow())},calcFirstSlide:function(){var a,b=this.opts();a=parseInt(b.startingSlide||
0,10);(a>=b.slides.length||0>a)&&(a=0);b.currSlide=a;b.reverse?(b.nextSlide=a-1,0>b.nextSlide&&(b.nextSlide=b.slides.length-1)):(b.nextSlide=a+1,b.nextSlide==b.slides.length&&(b.nextSlide=0))},calcNextSlide:function(){var a,b=this.opts();b.reverse?(a=0>b.nextSlide-1,b.nextSlide=a?b.slideCount-1:b.nextSlide-1,b.currSlide=a?0:b.nextSlide+1):(a=b.nextSlide+1==b.slides.length,b.nextSlide=a?0:b.nextSlide+1,b.currSlide=a?b.slides.length-1:b.nextSlide-1)},calcTx:function(a,d){var c;return a._tempFx?c=b.fn.cycle.transitions[a._tempFx]:
d&&a.manualFx&&(c=b.fn.cycle.transitions[a.manualFx]),c||(c=b.fn.cycle.transitions[a.fx]),a._tempFx=null,this.opts()._tempFx=null,c||(c=b.fn.cycle.transitions.fade,a.API.log('Transition "'+a.fx+'" not found.  Using fade.')),c},prepareTx:function(a,b){var c,e,h,f,l,k=this.opts();return 2>k.slideCount?void(k.timeoutId=0):(!a||k.busy&&!k.manualTrump||(k.API.stopTransition(),k.busy=!1,clearTimeout(k.timeoutId),k.timeoutId=0),void(k.busy||(0!==k.timeoutId||a)&&(e=k.slides[k.currSlide],h=k.slides[k.nextSlide],
f=k.API.getSlideOpts(k.nextSlide),l=k.API.calcTx(f,a),k._tx=l,a&&void 0!==f.manualSpeed&&(f.speed=f.manualSpeed),k.nextSlide!=k.currSlide&&(a||!k.paused&&!k.hoverPaused&&k.timeout)?(k.API.trigger("cycle-before",[f,e,h,b]),l.before&&l.before(f,e,h,b),c=function(){k.busy=!1;k.container.data("cycle.opts")&&(l.after&&l.after(f,e,h,b),k.API.trigger("cycle-after",[f,e,h,b]),k.API.queueTransition(f),k.API.updateView(!0))},k.busy=!0,l.transition?l.transition(f,e,h,b,c):k.API.doTransition(f,e,h,b,c),k.API.calcNextSlide(),
k.API.updateView()):k.API.queueTransition(f))))},doTransition:function(a,d,c,e,h){var f=b(d),l=b(c),k=function(){l.animate(a.animIn||{opacity:1},a.speed,a.easeIn||a.easing,h)};l.css(a.cssBefore||{});f.animate(a.animOut||{},a.speed,a.easeOut||a.easing,function(){f.css(a.cssAfter||{});a.sync||k()});a.sync&&k()},queueTransition:function(a,d){var c=this.opts(),e=void 0!==d?d:a.timeout;return 0===c.nextSlide&&0===--c.loop?(c.API.log("terminating; loop=0"),c.timeout=0,e?setTimeout(function(){c.API.trigger("cycle-finished",
[c])},e):c.API.trigger("cycle-finished",[c]),void(c.nextSlide=c.currSlide)):void 0!==c.continueAuto&&(!1===c.continueAuto||b.isFunction(c.continueAuto)&&!1===c.continueAuto())?(c.API.log("terminating automatic transitions"),c.timeout=0,void(c.timeoutId&&clearTimeout(c.timeoutId))):void(e&&(c._lastQueue=b.now(),void 0===d&&(c._remainingTimeout=a.timeout),c.paused||c.hoverPaused||(c.timeoutId=setTimeout(function(){c.API.prepareTx(!1,!c.reverse)},e))))},stopTransition:function(){var a=this.opts();a.slides.filter(":animated").length&&
(a.slides.stop(!1,!0),a.API.trigger("cycle-transition-stopped",[a]));a._tx&&a._tx.stopTransition&&a._tx.stopTransition(a)},advanceSlide:function(a){var b=this.opts();return clearTimeout(b.timeoutId),b.timeoutId=0,b.nextSlide=b.currSlide+a,0>b.nextSlide?b.nextSlide=b.slides.length-1:b.nextSlide>=b.slides.length&&(b.nextSlide=0),b.API.prepareTx(!0,0<=a),!1},buildSlideOpts:function(a){var d,g,e=this.opts();a=a.data()||{};for(var h in a)a.hasOwnProperty(h)&&/^cycle[A-Z]+/.test(h)&&(d=a[h],g=h.match(/^cycle(.*)/)[1].replace(/^[A-Z]/,
c),e.API.log("["+(e.slideCount-1)+"]",g+":",d,"("+typeof d+")"),a[g]=d);a=b.extend({},b.fn.cycle.defaults,e,a);a.slideNum=e.slideCount;try{delete a.API,delete a.slideCount,delete a.currSlide,delete a.nextSlide,delete a.slides}catch(f){}return a},getSlideOpts:function(a){var d=this.opts();void 0===a&&(a=d.currSlide);a=b(d.slides[a]).data("cycle.opts");return b.extend({},d,a)},initSlide:function(a,d,c){var e=this.opts();d.css(a.slideCss||{});0<c&&d.css("zIndex",c);isNaN(a.speed)&&(a.speed=b.fx.speeds[a.speed]||
b.fx.speeds._default);a.sync||(a.speed/=2);d.addClass(e.slideClass)},updateView:function(a,b){var c=this.opts();if(c._initialized){var e=c.API.getSlideOpts(),h=c.slides[c.currSlide];!a&&!0!==b&&(c.API.trigger("cycle-update-view-before",[c,e,h]),0>c.updateView)||(c.slideActiveClass&&c.slides.removeClass(c.slideActiveClass).eq(c.currSlide).addClass(c.slideActiveClass),a&&c.hideNonActive&&c.slides.filter(":not(."+c.slideActiveClass+")").css("visibility","hidden"),0===c.updateView&&setTimeout(function(){c.API.trigger("cycle-update-view",
[c,e,h,a])},e.speed/(c.sync?2:1)),0!==c.updateView&&c.API.trigger("cycle-update-view",[c,e,h,a]),a&&c.API.trigger("cycle-update-view-after",[c,e,h]))}},getComponent:function(a){var d=this.opts();a=d[a];return"string"==typeof a?/^\s*[\>|\+|~]/.test(a)?d.container.find(a):b(a):a.jquery?a:b(a)},stackSlides:function(a,d,c){var e=this.opts();a||(a=e.slides[e.currSlide],d=e.slides[e.nextSlide],c=!e.reverse);b(a).css("zIndex",e.maxZ);a=e.maxZ-2;var h=e.slideCount;if(c){for(c=e.currSlide+1;h>c;c++)b(e.slides[c]).css("zIndex",
a--);for(c=0;c<e.currSlide;c++)b(e.slides[c]).css("zIndex",a--)}else{for(c=e.currSlide-1;0<=c;c--)b(e.slides[c]).css("zIndex",a--);for(c=h-1;c>e.currSlide;c--)b(e.slides[c]).css("zIndex",a--)}b(d).css("zIndex",e.maxZ-1)},getSlideIndex:function(a){return this.opts().slides.index(a)}};b.fn.cycle.log=function(){window.console&&console.log&&console.log("[cycle2] "+Array.prototype.join.call(arguments," "))};b.fn.cycle.version=function(){return"Cycle2: 2.1.6"};b.fn.cycle.transitions={custom:{},none:{before:function(a,
b,c,e){a.API.stackSlides(c,b,e);a.cssBefore={opacity:1,visibility:"visible",display:"block"}}},fade:{before:function(a,d,c,e){var h=a.API.getSlideOpts(a.nextSlide).slideCss||{};a.API.stackSlides(d,c,e);a.cssBefore=b.extend(h,{opacity:0,visibility:"visible",display:"block"});a.animIn={opacity:1};a.animOut={opacity:0}}},fadeout:{before:function(a,d,c,e){var h=a.API.getSlideOpts(a.nextSlide).slideCss||{};a.API.stackSlides(d,c,e);a.cssBefore=b.extend(h,{opacity:1,visibility:"visible",display:"block"});
a.animOut={opacity:0}}},scrollHorz:{before:function(a,b,c,e){a.API.stackSlides(b,c,e);b=a.container.css("overflow","hidden").width();a.cssBefore={left:e?b:-b,top:0,opacity:1,visibility:"visible",display:"block"};a.cssAfter={zIndex:a._maxZ-2,left:0};a.animIn={left:0};a.animOut={left:e?-b:b}}}};b.fn.cycle.defaults={allowWrap:!0,autoSelector:".cycle-slideshow[data-cycle-auto-init!=false]",delay:0,easing:null,fx:"fade",hideNonActive:!0,loop:0,manualFx:void 0,manualSpeed:void 0,manualTrump:!0,maxZ:100,
pauseOnHover:!1,reverse:!1,slideActiveClass:"cycle-slide-active",slideClass:"cycle-slide",slideCss:{position:"absolute",top:0,left:0},slides:"> img",speed:500,startingSlide:0,sync:!0,timeout:4E3,updateView:0};b(document).ready(function(){b(b.fn.cycle.defaults.autoSelector).cycle()})}(jQuery);
(function(b){function c(d,c){var f,g=c.autoHeight;"container"==g?(f=b(c.slides[c.currSlide]).outerHeight(),c.container.height(f)):c._autoHeightRatio?c.container.height(c.container.width()/c._autoHeightRatio):("calc"===g||"number"==b.type(g)&&0<=g)&&(f="calc"===g?a(d,c):g>=c.slides.length?0:g,f!=c._sentinelIndex)&&(c._sentinelIndex=f,c._sentinel&&c._sentinel.remove(),f=b(c.slides[f].cloneNode(!0)),f.removeAttr("id name rel").find("[id],[name],[rel]").removeAttr("id name rel"),f.css({position:"static",
visibility:"hidden",display:"block"}).prependTo(c.container).addClass("cycle-sentinel cycle-slide").removeClass("cycle-slide-active"),f.find("*").css("visibility","hidden"),c._sentinel=f)}function a(a,d){var c=0,g=-1;return d.slides.each(function(a){var d=b(this).height();d>g&&(g=d,c=a)}),c}function d(a,d,c,g){a=b(g).outerHeight();d.container.animate({height:a},d.autoHeightSpeed,d.autoHeightEasing)}function g(a,h){h._autoHeightOnResize&&(b(window).off("resize orientationchange",h._autoHeightOnResize),
h._autoHeightOnResize=null);h.container.off("cycle-slide-added cycle-slide-removed",c);h.container.off("cycle-destroyed",g);h.container.off("cycle-before",d);h._sentinel&&(h._sentinel.remove(),h._sentinel=null)}b.extend(b.fn.cycle.defaults,{autoHeight:0,autoHeightSpeed:250,autoHeightEasing:null});b(document).on("cycle-initialized",function(a,h){function f(){c(a,h)}var l,k=h.autoHeight,n=b.type(k),r=null;"string"!==n&&"number"!==n||(h.container.on("cycle-slide-added cycle-slide-removed",c),h.container.on("cycle-destroyed",
g),"container"==k?h.container.on("cycle-before",d):"string"===n&&/\d+\:\d+/.test(k)&&(l=k.match(/(\d+)\:(\d+)/),l=l[1]/l[2],h._autoHeightRatio=l),"number"!==n&&(h._autoHeightOnResize=function(){clearTimeout(r);r=setTimeout(f,50)},b(window).on("resize orientationchange",h._autoHeightOnResize)),setTimeout(f,30))})})(jQuery);
(function(b){b.extend(b.fn.cycle.defaults,{caption:"> .cycle-caption",captionTemplate:"{{slideNum}} / {{slideCount}}",overlay:"> .cycle-overlay",overlayTemplate:"<div>{{title}}</div><div>{{desc}}</div>",captionModule:"caption"});b(document).on("cycle-update-view",function(c,a,d,g){"caption"===a.captionModule&&b.each(["caption","overlay"],function(){var b=d[this+"Template"],c=a.API.getComponent(this);c.length&&b?(c.html(a.API.tmpl(b,d,a,g)),c.show()):c.hide()})});b(document).on("cycle-destroyed",function(c,
a){var d;b.each(["caption","overlay"],function(){var b=a[this+"Template"];a[this]&&b&&(d=a.API.getComponent("caption"),d.empty())})})})(jQuery);
(function(b){var c=b.fn.cycle;b.fn.cycle=function(a){var d,g,e,h=b.makeArray(arguments);return"number"==b.type(a)?this.cycle("goto",a):"string"==b.type(a)?this.each(function(){var f;return d=a,e=b(this).data("cycle.opts"),void 0===e?void c.log('slideshow must be initialized before sending commands; "'+d+'" ignored'):(d="goto"==d?"jump":d,g=e.API[d],b.isFunction(g)?(f=b.makeArray(h),f.shift(),g.apply(e.API,f)):void c.log("unknown command: ",d))}):c.apply(this,arguments)};b.extend(b.fn.cycle,c);b.extend(c.API,
{next:function(){var a=this.opts();if(!a.busy||a.manualTrump){var b=a.reverse?-1:1;!1===a.allowWrap&&a.currSlide+b>=a.slideCount||(a.API.advanceSlide(b),a.API.trigger("cycle-next",[a]).log("cycle-next"))}},prev:function(){var a=this.opts();if(!a.busy||a.manualTrump){var b=a.reverse?1:-1;!1===a.allowWrap&&0>a.currSlide+b||(a.API.advanceSlide(b),a.API.trigger("cycle-prev",[a]).log("cycle-prev"))}},destroy:function(){this.stop();var a=this.opts(),d=b.isFunction(b._data)?b._data:b.noop;clearTimeout(a.timeoutId);
a.timeoutId=0;a.API.stop();a.API.trigger("cycle-destroyed",[a]).log("cycle-destroyed");a.container.removeData();d(a.container[0],"parsedAttrs",!1);a.retainStylesOnDestroy||(a.container.removeAttr("style"),a.slides.removeAttr("style"),a.slides.removeClass(a.slideActiveClass));a.slides.each(function(){var c=b(this);c.removeData();c.removeClass(a.slideClass);d(this,"parsedAttrs",!1)})},jump:function(a,b){var c,e=this.opts();if(!e.busy||e.manualTrump){c=parseInt(a,10);if(isNaN(c)||0>c||c>=e.slides.length)return void e.API.log("goto: invalid slide index: "+
c);if(c==e.currSlide)return void e.API.log("goto: skipping, already on slide",c);e.nextSlide=c;clearTimeout(e.timeoutId);e.timeoutId=0;e.API.log("goto: ",c," (zero-index)");c=e.currSlide<e.nextSlide;e._tempFx=b;e.API.prepareTx(!0,c)}},stop:function(){var a=this.opts(),d=a.container;clearTimeout(a.timeoutId);a.timeoutId=0;a.API.stopTransition();a.pauseOnHover&&(!0!==a.pauseOnHover&&(d=b(a.pauseOnHover)),d.off("mouseenter mouseleave"));a.API.trigger("cycle-stopped",[a]).log("cycle-stopped")},reinit:function(){var b=
this.opts();b.API.destroy();b.container.cycle()},remove:function(a){for(var d,c,e=this.opts(),h=[],f=1,l=0;l<e.slides.length;l++)d=e.slides[l],l==a?c=d:(h.push(d),b(d).data("cycle.opts").slideNum=f,f++);c&&(e.slides=b(h),e.slideCount--,b(c).remove(),a==e.currSlide?e.API.advanceSlide(1):a<e.currSlide?e.currSlide--:e.currSlide++,e.API.trigger("cycle-slide-removed",[e,a,c]).log("cycle-slide-removed"),e.API.updateView())}});b(document).on("click.cycle","[data-cycle-cmd]",function(a){a.preventDefault();
a=b(this);var d=a.data("cycle-cmd"),c=a.data("cycle-context")||".cycle-slideshow";b(c).cycle(d,a.data("cycle-arg"))})})(jQuery);
(function(b){function c(a,d){var c;return a._hashFence?void(a._hashFence=!1):(c=window.location.hash.substring(1),void a.slides.each(function(e){if(b(this).data("cycle-hash")==c){if(!0===d)a.startingSlide=e;else{var h=a.currSlide<e;a.nextSlide=e;a.API.prepareTx(!0,h)}return!1}}))}b(document).on("cycle-pre-initialize",function(a,d){c(d,!0);d._onHashChange=function(){c(d,!1)};b(window).on("hashchange",d._onHashChange)});b(document).on("cycle-update-view",function(b,d,c){c.hash&&"#"+c.hash!=window.location.hash&&
(d._hashFence=!0,window.location.hash=c.hash)});b(document).on("cycle-destroyed",function(a,d){d._onHashChange&&b(window).off("hashchange",d._onHashChange)})})(jQuery);
(function(b){b.extend(b.fn.cycle.defaults,{loader:!1});b(document).on("cycle-bootstrap",function(c,a){function d(d,c){function f(d){var e;"wait"==a.loader?(k.push(d),0===r&&(k.sort(l),g.apply(a.API,[k,c]),a.container.removeClass("cycle-loading"))):(e=b(a.slides[a.currSlide]),g.apply(a.API,[d,c]),e.show(),a.container.removeClass("cycle-loading"))}function l(b,a){return b.data("index")-a.data("index")}var k=[];if("string"==b.type(d))d=b.trim(d);else if("array"===b.type(d))for(var n=0;n<d.length;n++)d[n]=
b(d[n])[0];d=b(d);var r=d.length;r&&(d.css("visibility","hidden").appendTo("body").each(function(d){var e=0,l=b(this),n=l.is("img")?l:l.find("img");return l.data("index",d),n=n.filter(":not(.cycle-loader-ignore)").filter(':not([src=""])'),n.length?(e=n.length,void n.each(function(){if(this.complete)0===--e&&(--r,f(l));else b(this).load(function(){0===--e&&(--r,f(l))}).on("error",function(){0===--e&&(a.API.log("slide skipped; img not loaded:",this.src),0===--r&&"wait"==a.loader&&g.apply(a.API,[k,c]))})})):
(--r,void k.push(l))}),r&&a.container.addClass("cycle-loading"))}var g;a.loader&&(g=a.API.add,a.API.add=d)})})(jQuery);
(function(b){function c(a,c,e){var h;a.API.getComponent("pager").each(function(){var f=b(this);if(c.pagerTemplate){var l=a.API.tmpl(c.pagerTemplate,c,a,e[0]);h=b(l).appendTo(f)}else h=f.children().eq(a.slideCount-1);h.on(a.pagerEvent,function(b){a.pagerEventBubble||b.preventDefault();a.API.page(f,b.currentTarget)})})}function a(b,a){var c=this.opts();if(!c.busy||c.manualTrump){var h=b.children().index(a),f=c.currSlide<h;c.currSlide!=h&&(c.nextSlide=h,c._tempFx=c.pagerFx,c.API.prepareTx(!0,f),c.API.trigger("cycle-pager-activated",
[c,b,a]))}}b.extend(b.fn.cycle.defaults,{pager:"> .cycle-pager",pagerActiveClass:"cycle-pager-active",pagerEvent:"click.cycle",pagerEventBubble:void 0,pagerTemplate:"<span>&bull;</span>"});b(document).on("cycle-bootstrap",function(b,a,e){e.buildPagerLink=c});b(document).on("cycle-slide-added",function(b,c,e,h){c.pager&&(c.API.buildPagerLink(c,e,h),c.API.page=a)});b(document).on("cycle-slide-removed",function(a,c,e){c.pager&&c.API.getComponent("pager").each(function(){var a=b(this);b(a.children()[e]).remove()})});
b(document).on("cycle-update-view",function(a,c){var e;c.pager&&(e=c.API.getComponent("pager"),e.each(function(){b(this).children().removeClass(c.pagerActiveClass).eq(c.currSlide).addClass(c.pagerActiveClass)}))});b(document).on("cycle-destroyed",function(b,a){var c=a.API.getComponent("pager");c&&(c.children().off(a.pagerEvent),a.pagerTemplate&&c.empty())})})(jQuery);
(function(b){b.extend(b.fn.cycle.defaults,{next:"> .cycle-next",nextEvent:"click.cycle",disabledClass:"disabled",prev:"> .cycle-prev",prevEvent:"click.cycle",swipe:!1});b(document).on("cycle-initialized",function(b,a){if(a.API.getComponent("next").on(a.nextEvent,function(b){b.preventDefault();a.API.next()}),a.API.getComponent("prev").on(a.prevEvent,function(b){b.preventDefault();a.API.prev()}),a.swipe){var d=a.swipeVert?"swipeDown.cycle":"swipeRight.cycle swiperight.cycle";a.container.on(a.swipeVert?
"swipeUp.cycle":"swipeLeft.cycle swipeleft.cycle",function(){a._tempFx=a.swipeFx;a.API.next()});a.container.on(d,function(){a._tempFx=a.swipeFx;a.API.prev()})}});b(document).on("cycle-update-view",function(b,a){if(!a.allowWrap){var d=a.disabledClass,g=a.API.getComponent("next"),e=a.API.getComponent("prev"),h=a._prevBoundry||0;a.currSlide==(void 0!==a._nextBoundry?a._nextBoundry:a.slideCount-1)?g.addClass(d).prop("disabled",!0):g.removeClass(d).prop("disabled",!1);a.currSlide===h?e.addClass(d).prop("disabled",
!0):e.removeClass(d).prop("disabled",!1)}});b(document).on("cycle-destroyed",function(b,a){a.API.getComponent("prev").off(a.nextEvent);a.API.getComponent("next").off(a.prevEvent);a.container.off("swipeleft.cycle swiperight.cycle swipeLeft.cycle swipeRight.cycle swipeUp.cycle swipeDown.cycle")})})(jQuery);
(function(b){b.extend(b.fn.cycle.defaults,{progressive:!1});b(document).on("cycle-pre-initialize",function(c,a){if(a.progressive){var d,g,e=a.API,h=e.next,f=e.prev,l=e.prepareTx,k=b.type(a.progressive);if("array"==k)d=a.progressive;else if(b.isFunction(a.progressive))d=a.progressive(a);else if("string"==k){if(g=b(a.progressive),d=b.trim(g.html()),!d)return;if(/^(\[)/.test(d))try{d=b.parseJSON(d)}catch(n){return void e.log("error parsing progressive slides",n)}else d=d.split(new RegExp(g.data("cycle-split")||
"\n")),d[d.length-1]||d.pop()}l&&(e.prepareTx=function(b,c){var e,f;return b||0===d.length?void l.apply(a.API,[b,c]):void(c&&a.currSlide==a.slideCount-1?(f=d[0],d=d.slice(1),a.container.one("cycle-slide-added",function(b,a){setTimeout(function(){a.API.advanceSlide(1)},50)}),a.API.add(f)):c||0!==a.currSlide?l.apply(a.API,[b,c]):(e=d.length-1,f=d[e],d=d.slice(0,e),a.container.one("cycle-slide-added",function(b,a){setTimeout(function(){a.currSlide=1;a.API.advanceSlide(-1)},50)}),a.API.add(f,!0)))});
h&&(e.next=function(){var b=this.opts();if(d.length&&b.currSlide==b.slideCount-1){var a=d[0];d=d.slice(1);b.container.one("cycle-slide-added",function(b,a){h.apply(a.API);a.container.removeClass("cycle-loading")});b.container.addClass("cycle-loading");b.API.add(a)}else h.apply(b.API)});f&&(e.prev=function(){var b=this.opts();if(d.length&&0===b.currSlide){var a=d.length-1,c=d[a];d=d.slice(0,a);b.container.one("cycle-slide-added",function(b,a){a.currSlide=1;a.API.advanceSlide(-1);a.container.removeClass("cycle-loading")});
b.container.addClass("cycle-loading");b.API.add(c,!0)}else f.apply(b.API)})}})})(jQuery);
(function(b){b.extend(b.fn.cycle.defaults,{tmplRegex:"{{((.)?.*?)}}"});b.extend(b.fn.cycle.API,{tmpl:function(c,a){var d=new RegExp(a.tmplRegex||b.fn.cycle.defaults.tmplRegex,"g"),g=b.makeArray(arguments);return g.shift(),c.replace(d,function(a,c){var d,l,k,n,r=c.split(".");for(d=0;d<g.length;d++)if(k=g[d]){if(1<r.length)for(n=k,l=0;l<r.length;l++)k=n,n=n[r[l]]||c;else n=k[c];if(b.isFunction(n))return n.apply(k,g);if(void 0!==n&&null!==n&&n!=c)return n}return c})}})})(jQuery);
(function(b,c,a,d,g){var e=b(c),h=b(a);b.fn.fullpage=function(f){function l(b){b.find(".fp-slides").after('<div class="fp-controlArrow fp-prev"></div><div class="fp-controlArrow fp-next"></div>');"#fff"!=f.controlArrowColor&&(b.find(".fp-controlArrow.fp-next").css("border-color","transparent transparent transparent "+f.controlArrowColor),b.find(".fp-controlArrow.fp-prev").css("border-color","transparent "+f.controlArrowColor+" transparent transparent"));f.loopHorizontal||b.find(".fp-controlArrow.fp-prev").hide()}
function k(){D.append('<div id="fp-nav"><ul></ul></div>');O=b("#fp-nav");O.addClass(function(){return f.showActiveTooltip?"fp-show-active "+f.navigationPosition:f.navigationPosition});for(var a=0;a<b(".fp-section").length;a++){var c="";f.anchors.length&&(c=f.anchors[a]);var c='<li><a href="#'+c+'"><span></span></a>',d=f.navigationTooltips[a];"undefined"!==typeof d&&""!==d&&(c+='<div class="fp-tooltip '+f.navigationPosition+'">'+d+"</div>");c+="</li>";O.find("ul").append(c)}}function n(){b(".fp-section").each(function(){var a=
b(this).find(".fp-slide");a.length?a.each(function(){aa(b(this))}):aa(b(this))});b.isFunction(f.afterRender)&&f.afterRender.call(this)}function r(){var c;if(!f.autoScrolling||f.scrollBar){for(var W=e.scrollTop(),g=0,h=d.abs(W-a.querySelectorAll(".fp-section")[0].offsetTop),k=a.querySelectorAll(".fp-section"),l=0;l<k.length;++l){var n=d.abs(W-k[l].offsetTop);n<h&&(g=l,h=n)}c=b(k).eq(g)}if(!f.autoScrolling||f.scrollBar){if(!c.hasClass("active")){pa=!0;W=b(".fp-section.active");g=W.index(".fp-section")+
1;h=la(c);k=c.data("anchor");l=c.index(".fp-section")+1;n=c.find(".fp-slide.active");if(n.length)var m=n.data("anchor"),p=n.index();G&&(c.addClass("active").siblings().removeClass("active"),b.isFunction(f.onLeave)&&f.onLeave.call(W,g,l,h),b.isFunction(f.afterLoad)&&f.afterLoad.call(c,k,l),Z(k,l-1),f.anchors.length&&(P=k,oa(p,m,k,l)));clearTimeout(Aa);Aa=setTimeout(function(){pa=!1},100)}f.fitToSection&&(clearTimeout(Ba),Ba=setTimeout(function(){G&&(b(".fp-section.active").is(c)&&(H=!0),w(c),H=!1)},
1E3))}}function x(b){return b.find(".fp-slides").length?b.find(".fp-slide.active").find(".fp-scrollable"):b.find(".fp-scrollable")}function y(b,a){if(I[b]){var c,d;"down"==b?(c="bottom",d=q.moveSectionDown):(c="top",d=q.moveSectionUp);if(0<a.length)if(c="top"===c?!a.scrollTop():"bottom"===c?a.scrollTop()+1+a.innerHeight()>=a[0].scrollHeight:void 0,c)d();else return!0;else d()}}function L(a){var c=a.originalEvent;if(!S(a.target)&&A(c)){f.autoScrolling&&a.preventDefault();a=b(".fp-section.active");
var g=x(a);G&&!Q&&(c=Ca(c),X=c.y,da=c.x,a.find(".fp-slides").length&&d.abs(ea-da)>d.abs(Y-X)?d.abs(ea-da)>e.width()/100*f.touchSensitivity&&(ea>da?I.right&&q.moveSlideRight():I.left&&q.moveSlideLeft()):f.autoScrolling&&d.abs(Y-X)>e.height()/100*f.touchSensitivity&&(Y>X?y("down",g):X>Y&&y("up",g)))}}function S(a,c){c=c||0;var d=b(a).parent();return c<f.normalScrollElementTouchThreshold&&d.is(f.normalScrollElements)?!0:c==f.normalScrollElementTouchThreshold?!1:S(d,++c)}function A(a){return"undefined"===
typeof a.pointerType||"mouse"!=a.pointerType}function U(a){a=a.originalEvent;f.fitToSection&&J.stop();A(a)&&(a=Ca(a),Y=a.y,ea=a.x)}function M(a,b){for(var c=0,e=a.slice(d.max(a.length-b,1)),f=0;f<e.length;f++)c+=e[f];return d.ceil(c/b)}function m(a){var e=(new Date).getTime();if(f.autoScrolling){a=c.event||a;var g=a.wheelDelta||-a.deltaY||-a.detail,h=d.max(-1,d.min(1,g));149<R.length&&R.shift();R.push(d.abs(g));f.scrollBar&&(a.preventDefault?a.preventDefault():a.returnValue=!1);a=b(".fp-section.active");
a=x(a);g=e-Da;Da=e;200<g&&(R=[]);G&&(e=M(R,10),g=M(R,70),e>=g&&(0>h?y("down",a):y("up",a)));return!1}f.fitToSection&&J.stop()}function T(a){var c=b(".fp-section.active").find(".fp-slides");if(c.length&&!Q){var d=c.find(".fp-slide.active"),e=null,e="prev"===a?d.prev(".fp-slide"):d.next(".fp-slide");if(!e.length){if(!f.loopHorizontal)return;e="prev"===a?d.siblings(":last"):d.siblings(":first")}Q=!0;F(c,e)}}function N(){b(".fp-slide.active").each(function(){qa(b(this))})}function w(a,c,d){var g=a.position();
if("undefined"!==typeof g&&(c={element:a,callback:c,isMovementUp:d,dest:g,dtop:g.top,yMovement:la(a),anchorLink:a.data("anchor"),sectionIndex:a.index(".fp-section"),activeSlide:a.find(".fp-slide.active"),activeSection:b(".fp-section.active"),leavingSection:b(".fp-section.active").index(".fp-section")+1,localIsResizing:H},!(c.activeSection.is(a)&&!H||f.scrollBar&&e.scrollTop()===c.dtop))){if(c.activeSlide.length)var h=c.activeSlide.data("anchor"),k=c.activeSlide.index();f.autoScrolling&&f.continuousVertical&&
"undefined"!==typeof c.isMovementUp&&(!c.isMovementUp&&"up"==c.yMovement||c.isMovementUp&&"down"==c.yMovement)&&(c.isMovementUp?b(".fp-section.active").before(c.activeSection.nextAll(".fp-section")):b(".fp-section.active").after(c.activeSection.prevAll(".fp-section").get().reverse()),K(b(".fp-section.active").position().top),N(),c.wrapAroundElements=c.activeSection,c.dest=c.element.position(),c.dtop=c.dest.top,c.yMovement=la(c.element));a.addClass("active").siblings().removeClass("active");G=!1;oa(k,
h,c.anchorLink,c.sectionIndex);b.isFunction(f.onLeave)&&!c.localIsResizing&&f.onLeave.call(c.activeSection,c.leavingSection,c.sectionIndex+1,c.yMovement);u(c);P=c.anchorLink;Z(c.anchorLink,c.sectionIndex)}}function u(a){if(f.css3&&f.autoScrolling&&!f.scrollBar)ua("translate3d(0px, -"+a.dtop+"px, 0px)",!0),setTimeout(function(){z(a)},f.scrollingSpeed);else{var c=p(a);b(c.element).animate(c.options,f.scrollingSpeed,f.easing).promise().done(function(){z(a)})}}function p(a){var b={};f.autoScrolling&&
!f.scrollBar?(b.options={top:-a.dtop},b.element=".fullpage-wrapper"):(b.options={scrollTop:a.dtop},b.element="html, body");return b}function B(a){a.wrapAroundElements&&a.wrapAroundElements.length&&(a.isMovementUp?b(".fp-section:first").before(a.wrapAroundElements):b(".fp-section:last").after(a.wrapAroundElements),K(b(".fp-section.active").position().top),N())}function z(a){B(a);b.isFunction(f.afterLoad)&&!a.localIsResizing&&f.afterLoad.call(a.element,a.anchorLink,a.sectionIndex+1);G=!0;setTimeout(function(){b.isFunction(a.callback)&&
a.callback.call(this)},600)}function C(){if(!pa){var a=c.location.hash.replace("#","").split("/"),b=a[0],a=a[1];if(b.length){var d="undefined"===typeof P,e="undefined"===typeof P&&"undefined"===typeof a&&!Q;(b&&b!==P&&!d||e||!Q&&ra!=a)&&ma(b,a)}}}function v(a){G&&(a.pageY<fa?q.moveSectionUp():a.pageY>fa&&q.moveSectionDown());fa=a.pageY}function F(a,c){var d=c.position(),e=c.index(),g=a.closest(".fp-section"),h=g.index(".fp-section"),k=g.data("anchor"),l=g.find(".fp-slidesNav"),n=xa(c),m=H;if(f.onSlideLeave){var p=
g.find(".fp-slide.active"),v=p.index(),q;q=v==e?"none":v>e?"left":"right";m||"none"===q||b.isFunction(f.onSlideLeave)&&f.onSlideLeave.call(p,k,h+1,v,q)}c.addClass("active").siblings().removeClass("active");!f.loopHorizontal&&f.controlArrows&&(g.find(".fp-controlArrow.fp-prev").toggle(0!==e),g.find(".fp-controlArrow.fp-next").toggle(!c.is(":last-child")));g.hasClass("active")&&oa(e,n,k,h);var r=function(){m||b.isFunction(f.afterSlideLoad)&&f.afterSlideLoad.call(c,k,h+1,n,e);Q=!1};f.css3?(d="translate3d(-"+
d.left+"px, 0px, 0px)",ca(a.find(".fp-slidesContainer"),0<f.scrollingSpeed).css(Ea(d)),setTimeout(function(){r()},f.scrollingSpeed,f.easing)):a.animate({scrollLeft:d.left},f.scrollingSpeed,f.easing,function(){r()});l.find(".active").removeClass("active");l.find("li").eq(e).find("a").addClass("active")}function V(){ba();if(ga){var c=b(a.activeElement);c.is("textarea")||c.is("input")||c.is("select")||(c=e.height(),d.abs(c-sa)>20*d.max(sa,c)/100&&(q.reBuild(!0),sa=c))}else clearTimeout(Fa),Fa=setTimeout(function(){q.reBuild(!0)},
500)}function ba(){if(f.responsive){var a=t.hasClass("fp-responsive");e.width()<f.responsive?a||(q.setAutoScrolling(!1,"internal"),q.setFitToSection(!1,"internal"),b("#fp-nav").hide(),t.addClass("fp-responsive")):a&&(q.setAutoScrolling(ha.autoScrolling,"internal"),q.setFitToSection(ha.autoScrolling,"internal"),b("#fp-nav").show(),t.removeClass("fp-responsive"))}}function ca(a){var b="all "+f.scrollingSpeed+"ms "+f.easingcss3;a.removeClass("fp-notransition");return a.css({"-webkit-transition":b,transition:b})}
function na(a,b){if(825>a||900>b){var c=d.min(100*a/825,100*b/900).toFixed(2);D.css("font-size",c+"%")}else D.css("font-size","100%")}function Z(a,c){f.menu&&(b(f.menu).find(".active").removeClass("active"),b(f.menu).find('[data-menuanchor="'+a+'"]').addClass("active"));f.navigation&&(b("#fp-nav").find(".active").removeClass("active"),a?b("#fp-nav").find('a[href="#'+a+'"]').addClass("active"):b("#fp-nav").find("li").eq(c).find("a").addClass("active"))}function la(a){var c=b(".fp-section.active").index(".fp-section");
a=a.index(".fp-section");return c==a?"none":c>a?"up":"down"}function aa(a){a.css("overflow","hidden");var b=a.closest(".fp-section"),c=a.find(".fp-scrollable"),d;c.length?d=c.get(0).scrollHeight:(d=a.get(0).scrollHeight,f.verticalCentered&&(d=a.find(".fp-tableCell").get(0).scrollHeight));b=E-parseInt(b.css("padding-bottom"))-parseInt(b.css("padding-top"));d>b?c.length?c.css("height",b+"px").parent().css("height",b+"px"):(f.verticalCentered?a.find(".fp-tableCell").wrapInner('<div class="fp-scrollable" />'):
a.wrapInner('<div class="fp-scrollable" />'),a.find(".fp-scrollable").slimScroll({allowPageScroll:!0,height:b+"px",size:"10px",alwaysVisible:!0})):va(a);a.css("overflow","")}function va(a){a.find(".fp-scrollable").children().first().unwrap().unwrap();a.find(".slimScrollBar").remove();a.find(".slimScrollRail").remove()}function wa(a){a.addClass("fp-table").wrapInner('<div class="fp-tableCell" style="height:'+ta(a)+'px;" />')}function ta(a){var b=E;if(f.paddingTop||f.paddingBottom)b=a,b.hasClass("fp-section")||
(b=a.closest(".fp-section")),a=parseInt(b.css("padding-top"))+parseInt(b.css("padding-bottom")),b=E-a;return b}function ua(a,b){b?ca(t):t.addClass("fp-notransition");t.css(Ea(a));setTimeout(function(){t.removeClass("fp-notransition")},10)}function ma(a,c){var d;"undefined"===typeof c&&(c=0);d=isNaN(a)?b('[data-anchor="'+a+'"]'):b(".fp-section").eq(a-1);a===P||d.hasClass("active")?ya(d,c):w(d,function(){ya(d,c)})}function ya(a,b){if("undefined"!=typeof b){var c=a.find(".fp-slides"),d=c.find('[data-anchor="'+
b+'"]');d.length||(d=c.find(".fp-slide").eq(b));d.length&&F(c,d)}}function Ja(a,b){a.append('<div class="fp-slidesNav"><ul></ul></div>');var c=a.find(".fp-slidesNav");c.addClass(f.slidesNavPosition);for(var d=0;d<b;d++)c.find("ul").append('<li><a href="#"><span></span></a></li>');c.css("margin-left","-"+c.width()/2+"px");c.find("li").first().find("a").addClass("active")}function oa(a,b,c,d){d="";f.anchors.length&&(a?("undefined"!==typeof c&&(d=c),"undefined"===typeof b&&(b=a),ra=b,za(d+"/"+b)):("undefined"!==
typeof a&&(ra=b),za(c)));Ga()}function za(a){if(f.recordHistory)location.hash=a;else if(ga||ia)history.replaceState(g,g,"#"+a);else{var b=c.location.href.split("#")[0];c.location.replace(b+"#"+a)}}function xa(a){var b=a.data("anchor");a=a.index();"undefined"===typeof b&&(b=a);return b}function Ga(){var a=b(".fp-section.active"),c=a.find(".fp-slide.active"),d=a.data("anchor"),e=xa(c),a=a.index(".fp-section"),a=String(a);f.anchors.length&&(a=d);c.length&&(a=a+"-"+e);a=a.replace("/","-").replace("#",
"");D[0].className=D[0].className.replace(RegExp("\\b\\s?fp-viewing-[^\\s]+\\b","g"),"");D.addClass("fp-viewing-"+a)}function Ka(){var b=a.createElement("p"),d,e={webkitTransform:"-webkit-transform",OTransform:"-o-transform",msTransform:"-ms-transform",MozTransform:"-moz-transform",transform:"transform"};a.body.insertBefore(b,null);for(var f in e)b.style[f]!==g&&(b.style[f]="translate3d(1px,1px,1px)",d=c.getComputedStyle(b).getPropertyValue(e[f]));a.body.removeChild(b);return d!==g&&0<d.length&&"none"!==
d}function La(){if(ga||ia){var a=Ha();b(".fullpage-wrapper").off("touchstart "+a.down).on("touchstart "+a.down,U);b(".fullpage-wrapper").off("touchmove "+a.move).on("touchmove "+a.move,L)}}function Ma(){if(ga||ia){var a=Ha();b(".fullpage-wrapper").off("touchstart "+a.down);b(".fullpage-wrapper").off("touchmove "+a.move)}}function Ha(){return c.PointerEvent?{down:"pointerdown",move:"pointermove"}:{down:"MSPointerDown",move:"MSPointerMove"}}function Ca(a){var b=[];b.y="undefined"!==typeof a.pageY&&
(a.pageY||a.pageX)?a.pageY:a.touches[0].pageY;b.x="undefined"!==typeof a.pageX&&(a.pageY||a.pageX)?a.pageX:a.touches[0].pageX;ia&&A(a)&&(b.y=a.touches[0].pageY,b.x=a.touches[0].pageX);return b}function qa(a){q.setScrollingSpeed(0,"internal");F(a.closest(".fp-slides"),a);q.setScrollingSpeed(ha.scrollingSpeed,"internal")}function K(a){f.scrollBar?t.scrollTop(a):f.css3?ua("translate3d(0px, -"+a+"px, 0px)",!1):t.css("top",-a)}function Ea(a){return{"-webkit-transform":a,"-moz-transform":a,"-ms-transform":a,
transform:a}}function Na(){K(0);b("#fp-nav, .fp-slidesNav, .fp-controlArrow").remove();b(".fp-section").css({height:"","background-color":"",padding:""});b(".fp-slide").css({width:""});t.css({height:"",position:"","-ms-touch-action":"","touch-action":""});b(".fp-section, .fp-slide").each(function(){va(b(this));b(this).removeClass("fp-table active")});t.addClass("fp-notransition");t.find(".fp-tableCell, .fp-slidesContainer, .fp-slides").each(function(){b(this).replaceWith(this.childNodes)});J.scrollTop(0)}
function ja(a,b,c){f[a]=b;"internal"!==c&&(ha[a]=b)}function ka(a,b){console&&console[a]&&console[a]("fullPage: "+b)}var J=b("html, body"),D=b("body"),q=b.fn.fullpage;f=b.extend({menu:!1,anchors:[],navigation:!1,navigationPosition:"right",navigationTooltips:[],showActiveTooltip:!1,slidesNavigation:!1,slidesNavPosition:"bottom",scrollBar:!1,css3:!0,scrollingSpeed:700,autoScrolling:!0,fitToSection:!0,easing:"easeInOutCubic",easingcss3:"ease",loopBottom:!1,loopTop:!1,loopHorizontal:!0,continuousVertical:!1,
normalScrollElements:null,scrollOverflow:!1,touchSensitivity:5,normalScrollElementTouchThreshold:5,keyboardScrolling:!0,animateAnchor:!0,recordHistory:!0,controlArrows:!0,controlArrowColor:"#fff",verticalCentered:!0,resize:!1,sectionsColor:[],paddingTop:0,paddingBottom:0,fixedElements:null,responsive:0,sectionSelector:".section",slideSelector:".slide",afterLoad:null,onLeave:null,afterRender:null,afterResize:null,afterReBuild:null,afterSlideLoad:null,onSlideLeave:null},f);(function(){f.continuousVertical&&
(f.loopTop||f.loopBottom)&&(f.continuousVertical=!1,ka("warn","Option `loopTop/loopBottom` is mutually exclusive with `continuousVertical`; `continuousVertical` disabled"));f.continuousVertical&&f.scrollBar&&(f.continuousVertical=!1,ka("warn","Option `scrollBar` is mutually exclusive with `continuousVertical`; `continuousVertical` disabled"));b.each(f.anchors,function(a,c){(b("#"+c).length||b('[name="'+c+'"]').length)&&ka("error","data-anchor tags can not have the same value as any `id` element on the site (or `name` element for IE).")})})();
b.extend(b.easing,{easeInOutCubic:function(a,b,c,d,e){return 1>(b/=e/2)?d/2*b*b*b+c:d/2*((b-=2)*b*b+2)+c}});b.extend(b.easing,{easeInQuart:function(a,b,c,d,e){return d*(b/=e)*b*b*b+c}});q.setAutoScrolling=function(a,c){ja("autoScrolling",a,c);var d=b(".fp-section.active");f.autoScrolling&&!f.scrollBar?(J.css({overflow:"hidden",height:"100%"}),q.setRecordHistory(f.recordHistory,"internal"),t.css({"-ms-touch-action":"none","touch-action":"none"}),d.length&&K(d.position().top)):(J.css({overflow:"visible",
height:"initial"}),q.setRecordHistory(!1,"internal"),t.css({"-ms-touch-action":"","touch-action":""}),K(0),d.length&&J.scrollTop(d.position().top))};q.setRecordHistory=function(a,b){ja("recordHistory",a,b)};q.setScrollingSpeed=function(a,b){ja("scrollingSpeed",a,b)};q.setFitToSection=function(a,b){ja("fitToSection",a,b)};q.setMouseWheelScrolling=function(b){b?a.addEventListener?(a.addEventListener("mousewheel",m,!1),a.addEventListener("wheel",m,!1)):a.attachEvent("onmousewheel",m):a.addEventListener?
(a.removeEventListener("mousewheel",m,!1),a.removeEventListener("wheel",m,!1)):a.detachEvent("onmousewheel",m)};q.setAllowScrolling=function(a,c){"undefined"!=typeof c?(c=c.replace(/ /g,"").split(","),b.each(c,function(b,c){switch(c){case "up":I.up=a;break;case "down":I.down=a;break;case "left":I.left=a;break;case "right":I.right=a;break;case "all":q.setAllowScrolling(a)}})):a?(q.setMouseWheelScrolling(!0),La()):(q.setMouseWheelScrolling(!1),Ma())};q.setKeyboardScrolling=function(a){f.keyboardScrolling=
a};q.moveSectionUp=function(){var a=b(".fp-section.active").prev(".fp-section");a.length||!f.loopTop&&!f.continuousVertical||(a=b(".fp-section").last());a.length&&w(a,null,!0)};q.moveSectionDown=function(){var a=b(".fp-section.active").next(".fp-section");a.length||!f.loopBottom&&!f.continuousVertical||(a=b(".fp-section").first());a.length&&w(a,null,!1)};q.moveTo=function(a,c){var d="",d=isNaN(a)?b('[data-anchor="'+a+'"]'):b(".fp-section").eq(a-1);"undefined"!==typeof c?ma(a,c):0<d.length&&w(d)};
q.moveSlideRight=function(){T("next")};q.moveSlideLeft=function(){T("prev")};q.reBuild=function(a){if(!t.hasClass("fp-destroyed")){H=!0;var c=e.width();E=e.height();f.resize&&na(E,c);b(".fp-section").each(function(){var a=b(this).find(".fp-slides"),c=b(this).find(".fp-slide");f.verticalCentered&&b(this).find(".fp-tableCell").css("height",ta(b(this))+"px");b(this).css("height",E+"px");f.scrollOverflow&&(c.length?c.each(function(){aa(b(this))}):aa(b(this)));1<c.length&&F(a,a.find(".fp-slide.active"))});
c=b(".fp-section.active");c.index(".fp-section")&&w(c);H=!1;b.isFunction(f.afterResize)&&a&&f.afterResize.call(t);b.isFunction(f.afterReBuild)&&!a&&f.afterReBuild.call(t)}};var Q=!1,ga=navigator.userAgent.match(/(iPhone|iPod|iPad|Android|playbook|silk|BlackBerry|BB10|Windows Phone|Tizen|Bada|webOS|IEMobile|Opera Mini)/),ia="ontouchstart"in c||0<navigator.msMaxTouchPoints||navigator.maxTouchPoints,t=b(this),E=e.height(),H=!1,P,ra,G=!0,R=[],O,I={up:!0,down:!0,left:!0,right:!0},ha=b.extend(!0,{},f);
b(this).length?(t.css({height:"100%",position:"relative"}),t.addClass("fullpage-wrapper"),b("html").addClass("fp-enabled")):ka("error","Error! Fullpage.js needs to be initialized with a selector. For example: $('#myContainer').fullpage();");f.css3&&(f.css3=Ka());q.setAllowScrolling(!0);t.removeClass("fp-destroyed");b(f.sectionSelector).each(function(){b(this).addClass("fp-section")});b(f.slideSelector).each(function(){b(this).addClass("fp-slide")});f.navigation&&k();b(".fp-section").each(function(a){var c=
b(this),d=b(this).find(".fp-slide"),e=d.length;a||0!==b(".fp-section.active").length||b(this).addClass("active");b(this).css("height",E+"px");f.paddingTop&&b(this).css("padding-top",f.paddingTop);f.paddingBottom&&b(this).css("padding-bottom",f.paddingBottom);"undefined"!==typeof f.sectionsColor[a]&&b(this).css("background-color",f.sectionsColor[a]);"undefined"!==typeof f.anchors[a]&&(b(this).attr("data-anchor",f.anchors[a]),b(this).hasClass("active")&&Z(f.anchors[a],a));if(0<e){a=100*e;var g=100/
e;d.wrapAll('<div class="fp-slidesContainer" />');d.parent().wrap('<div class="fp-slides" />');b(this).find(".fp-slidesContainer").css("width",a+"%");f.controlArrows&&1<e&&l(b(this));f.slidesNavigation&&Ja(b(this),e);d.each(function(a){b(this).css("width",g+"%");f.verticalCentered&&wa(b(this))});c=c.find(".fp-slide.active");c.length?qa(c):d.eq(0).addClass("active")}else f.verticalCentered&&wa(b(this))}).promise().done(function(){q.setAutoScrolling(f.autoScrolling,"internal");var d=b(".fp-section.active").find(".fp-slide.active");
d.length&&(0!==b(".fp-section.active").index(".fp-section")||0===b(".fp-section.active").index(".fp-section")&&0!==d.index())&&qa(d);f.fixedElements&&f.css3&&b(f.fixedElements).appendTo(D);f.navigation&&(O.css("margin-top","-"+O.height()/2+"px"),O.find("li").eq(b(".fp-section.active").index(".fp-section")).find("a").addClass("active"));f.menu&&f.css3&&b(f.menu).closest(".fullpage-wrapper").length&&b(f.menu).appendTo(D);f.scrollOverflow?("complete"===a.readyState&&n(),e.on("load",n)):b.isFunction(f.afterRender)&&
f.afterRender.call(t);ba();if(!f.animateAnchor&&(d=c.location.hash.replace("#","").split("/")[0],d.length)){var g=b('[data-anchor="'+d+'"]');g.length&&(f.autoScrolling?K(g.position().top):(K(0),J.scrollTop(g.position().top)),Z(d,null),b.isFunction(f.afterLoad)&&f.afterLoad.call(g,d,g.index(".fp-section")+1),g.addClass("active").siblings().removeClass("active"))}Ga();e.on("load",function(){var a=c.location.hash.replace("#","").split("/"),b=a[0],a=a[1];b&&ma(b,a)})});var Aa,Ba,pa=!1;e.on("scroll",r);
var Y=0,ea=0,X=0,da=0,Da=(new Date).getTime();e.on("hashchange",C);h.keydown(function(c){clearTimeout(Ia);var d=b(a.activeElement);d.is("textarea")||d.is("input")||d.is("select")||!f.keyboardScrolling||!f.autoScrolling||(-1<b.inArray(c.which,[40,38,32,33,34])&&c.preventDefault(),Ia=setTimeout(function(){var a=c.shiftKey;switch(c.which){case 38:case 33:q.moveSectionUp();break;case 32:if(a){q.moveSectionUp();break}case 40:case 34:q.moveSectionDown();break;case 36:q.moveTo(1);break;case 35:q.moveTo(b(".fp-section").length);
break;case 37:q.moveSlideLeft();break;case 39:q.moveSlideRight()}},150))});var Ia;t.mousedown(function(a){2==a.which&&(fa=a.pageY,t.on("mousemove",v))});t.mouseup(function(a){2==a.which&&t.off("mousemove")});var fa=0;h.on("click touchstart","#fp-nav a",function(a){a.preventDefault();a=b(this).parent().index();w(b(".fp-section").eq(a))});h.on("click touchstart",".fp-slidesNav a",function(a){a.preventDefault();a=b(this).closest(".fp-section").find(".fp-slides");var c=a.find(".fp-slide").eq(b(this).closest("li").index());
F(a,c)});f.normalScrollElements&&(h.on("mouseenter",f.normalScrollElements,function(){q.setMouseWheelScrolling(!1)}),h.on("mouseleave",f.normalScrollElements,function(){q.setMouseWheelScrolling(!0)}));b(".fp-section").on("click touchstart",".fp-controlArrow",function(){b(this).hasClass("fp-prev")?q.moveSlideLeft():q.moveSlideRight()});e.resize(V);var sa=E,Fa;q.destroy=function(a){q.setAutoScrolling(!1,"internal");q.setAllowScrolling(!1);q.setKeyboardScrolling(!1);t.addClass("fp-destroyed");e.off("scroll",
r).off("hashchange",C).off("resize",V);h.off("click","#fp-nav a").off("mouseenter","#fp-nav li").off("mouseleave","#fp-nav li").off("click",".fp-slidesNav a").off("mouseover",f.normalScrollElements).off("mouseout",f.normalScrollElements);b(".fp-section").off("click",".fp-controlArrow");a&&Na()}}})(jQuery,window,document,Math);
!function(b){var c=function(a,c){this.el=b(a);this.options=b.extend({},b.fn.typed.defaults,c);this.isInput=this.el.is("input");this.attr=this.options.attr;this.showCursor=this.isInput?!1:this.options.showCursor;this.elContent=this.attr?this.el.attr(this.attr):this.el.text();this.contentType=this.options.contentType;this.typeSpeed=this.options.typeSpeed;this.startDelay=this.options.startDelay;this.backSpeed=this.options.backSpeed;this.backDelay=this.options.backDelay;this.strings=this.options.strings;
this.stopNum=this.arrayPos=this.strPos=0;this.loop=this.options.loop;this.loopCount=this.options.loopCount;this.curLoop=0;this.stop=!1;this.cursorChar=this.options.cursorChar;this.build()};c.prototype={constructor:c,init:function(){var a=this;a.timeout=setTimeout(function(){a.typewrite(a.strings[a.arrayPos],a.strPos)},a.startDelay)},build:function(){!0===this.showCursor&&(this.cursor=b('<span class="typed-cursor">'+this.cursorChar+"</span>"),this.el.after(this.cursor));this.init()},typewrite:function(a,
b){if(!0!==this.stop){var c=Math.round(70*Math.random())+this.typeSpeed,e=this;e.timeout=setTimeout(function(){var c=0,f=a.substr(b);if("^"===f.charAt(0)){var g=1;/^\^\d+/.test(f)&&(f=/\d+/.exec(f)[0],g+=f.length,c=parseInt(f));a=a.substring(0,b)+a.substring(b+g)}if("html"===e.contentType&&(f=a.substr(b).charAt(0),"<"===f||"&"===f)){for(var k=g="",k="<"===f?">":";";a.substr(b).charAt(0)!==k;)g+=a.substr(b).charAt(0),b++;b++;g+=k}e.timeout=setTimeout(function(){if(b===a.length){e.options.onStringTyped(e.arrayPos);
if(e.arrayPos===e.strings.length-1&&(e.options.callback(),e.curLoop++,!1===e.loop||e.curLoop===e.loopCount))return;e.timeout=setTimeout(function(){e.backspace(a,b)},e.backDelay)}else{0===b&&e.options.preStringTyped(e.arrayPos);var c=a.substr(0,b+1);e.attr?e.el.attr(e.attr,c):e.isInput?e.el.val(c):"html"===e.contentType?e.el.html(c):e.el.text(c);b++;e.typewrite(a,b)}},c)},c)}},backspace:function(a,b){if(!0!==this.stop){var c=Math.round(70*Math.random())+this.backSpeed,e=this;e.timeout=setTimeout(function(){if("html"===
e.contentType&&">"===a.substr(b).charAt(0)){for(var c="";"<"!==a.substr(b).charAt(0);)c-=a.substr(b).charAt(0),b--;b--}c=a.substr(0,b);e.attr?e.el.attr(e.attr,c):e.isInput?e.el.val(c):"html"===e.contentType?e.el.html(c):e.el.text(c);b>e.stopNum?(b--,e.backspace(a,b)):b<=e.stopNum&&(e.arrayPos++,e.arrayPos===e.strings.length?(e.arrayPos=0,e.init()):e.typewrite(e.strings[e.arrayPos],b))},c)}},reset:function(){clearInterval(this.timeout);var a=this.el.attr("id");this.el.after('<span id="'+a+'"/>');this.el.remove();
"undefined"!==typeof this.cursor&&this.cursor.remove();this.options.resetCallback()}};b.fn.typed=function(a){return this.each(function(){var d=b(this),g=d.data("typed"),e="object"==typeof a&&a;g||d.data("typed",g=new c(this,e));if("string"==typeof a)g[a]()})};b.fn.typed.defaults={strings:["These are the default values...","You know what you should do?","Use your own!","Have a great day!"],typeSpeed:0,startDelay:0,backSpeed:0,backDelay:500,loop:!1,loopCount:!1,showCursor:!0,cursorChar:"|",attr:null,
contentType:"html",callback:function(){},preStringTyped:function(){},onStringTyped:function(){},resetCallback:function(){}}}(window.jQuery);
(function(b){function c(a,c,e,h){c=a.text().split(c);var f="";c.length&&(b(c).each(function(a,b){escapedItem=String(b).replace(/&amp;/g,"&").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"quot");f+='<span class="lettering '+e+(a+1)+'" data-'+e+'="'+escapedItem+'">'+b+"</span>"+h}),a.empty().append(f))}var a={init:function(){return this.each(function(){c(b(this),"","letters","")})},words:function(){return this.each(function(){c(b(this)," ","words"," ")})},lines:function(){return this.each(function(){c(b(this).children("br").replaceWith("eefec303079ad17405c889e092e105b0").end(),
"eefec303079ad17405c889e092e105b0","lines","")})}};b.fn.lettering=function(c){if(c&&a[c])return a[c].apply(this,Array.prototype.slice.call(arguments,0));if("letters"===c||!c)return a.init.apply(this,Array.prototype.slice.call(arguments,0));b.error("Method "+c+" does not exist on jQuery.lettering");return this}})(jQuery);
(function(b){b.fn.birdman=function(c){function a(a){a.css("visibility","visible").hide().fadeIn()}function d(a,b){return"undefined"!==typeof a?a:b}if(1<arguments.length)return b.error("Please pass in arguments as a single object."),this;c||(c={});c.method=d(c.method,"letters");var g=function(){var a=[].slice.call(arguments);return(0==a.length?[]:a.reduce(function(a,b){return a.length<b.length?a:b})).map(function(b,c){return a.map(function(a){return a[c]})})}("abcdefghijklmnopqrstuvwxyz".split(""),
"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("")).concat("0123456789".split("")).concat(["- + * _ ~ < > | . ? ! \u00a7 $ % & quot / ( ) [ ] { } =".split(" ")]);c.order=d(c.order,g);c.delay=d(c.delay,150);c.speedUp=d(c.speedUp,!0);b(this).lettering(c.method);b(this).children("span.lettering").css("visibility","hidden");result=[];that=b(this);c.order.forEach(function(a,d,e){"string"===typeof a&&(a=Array(a));var g=b([]);a.forEach(function(a,b,d){a=that.children("span.lettering[data-"+c.method+'="'+a+'"]');g=g.add(a)});
0<g.length&&result.push(g)});var e=c.delay;result.forEach(function(b,d,g){e=c.speedUp?e+(c.delay/2-c.delay/2/(result.length-1)*d):c.delay*d;setTimeout(a.bind(void 0,b),e)})}})(jQuery);
(function(){$(function(){$("body").on({mousewheel:function(a){"el"!=a.target.id&&(a.preventDefault(),a.stopPropagation())}});$(window).bind("load",function(){var a=$(".arrow-down"),b=$(".arrow-down1"),c=$(".total"),d=$(".counter");$("body").addClass("loaded");$(".loading").fadeOut();$("body").unbind("mousewheel");$(".section0").css("visibility","visible");$(".headnav").fadeIn("fast");c.fadeIn("fast");d.fadeIn("fast");b.fadeIn("fast");a.fadeIn("fast");$(".hidden-text-off,.hidden-text-on,.hidden-text-me").hide();
setTimeout(function(){$(".home-3-btns").css("opacity","0").addClass("slideDown");$("menu-bars").css("opacity","0").addClass("slideDown")},1600);$(".turn-off").mouseover(function(){$(".hidden-text-off").show()});$(".turn-off").mouseleave(function(){$(".hidden-text-off").hide()});$(".turn-on").mouseover(function(){$(".hidden-text-on").show()});$(".turn-on").mouseleave(function(){$(".hidden-text-on").hide()});$(".contact-me").mouseover(function(){$(".hidden-text-me").show()});$(".contact-me").mouseleave(function(){$(".hidden-text-me").hide()});
$(".titleBgSub").typed({strings:["Frontend Web Dev","HTML5 CSS JAVASCRIPT","UX &amp; UI","Press this Key"],typeSpeed:50,startDelay:1200,backSpeed:0,backDelay:1E3,loop:!1,loopCount:0,showCursor:!1,cursorChar:"|",attr:null,contentType:"html",callback:function(){},preStringTyped:function(){},onStringTyped:function(){},resetCallback:function(){}});1E3>document.documentElement.clientWidth&&(a.fadeOut("fast"),b.fadeOut("fast"));$(document).ready(function(){var a=document.createElement("audio");a.src="pressing-spacebar.mp3";
a.volume=.05;a.autoPlay=!1;a.preLoad=!0;$(".playSound").click(function(){a.play()})})});var b=document.createElement("audio"),c=$(".counter"),a=$(".arrow-down"),d=$(".Gl"),g=$(".return"),e=$("#home"),h=$("#about"),f=$("#wise"),l=$("#sine"),k=$("#styles"),n=$("#kraftwerk"),r=$("#his"),x=$("#misc"),y=$("#cncf"),L=$("#crowd"),S=$("#re-act"),A=$("#contact"),U=$(".turn-off"),M=$(".turn-on"),m=$("#abler"),T=$("#api"),N=$(".nothing"),w=$("#nothing"),u=$(".godard"),p=$(".author"),B=$(".music"),z=$("#neu"),
C=$(".birdman");U.on("click",function(){U.addClass("auto-normal");M.removeClass("auto-normal");$.fn.fullpage.setAutoScrolling(!1);$("body").css("overflow-x","hidden")});M.on("click",function(){M.addClass("auto-normal");U.removeClass("auto-normal");$.fn.fullpage.setAutoScrolling(!0)});m.click(function(){$(this).is(":checked")?$("#submitBtn").removeAttr("disabled"):$("#submitBtn").attr("disabled","disabled")});$("#fullpage").fullpage({anchors:"firstPage secondPage thirdPage fourthPage fifthPage sixthPage seventhPage eighthPage ninthPage tenthPage eleventhPage twelfthPage thirteenthPage fourteenthPage".split(" "),
sectionsColor:"#fff #252525 #fff #ebebeb #fff #ebebeb #fff #ebebeb #fff #ebebeb #fff #ebebeb #ffff #fff".split(" "),slidesNavigation:!0,slidesNavPosition:"bottom",scrollingSpeed:1E3,easing:"easeInOutExpo",keyboardScrolling:!0,responsive:1E3,touchSensitivity:10,autoScrolling:!0,animateAnchor:!0,afterLoad:function(m){"firstPage"===m&&(c.text("1"),a.css({color:"#333"}),d.css("color","#A8FFEE"),e.addClass("pulse-link"));"firstPage"!==m&&(d.css("color","#333"),$(".home-3-btnsmall").fadeIn(),e.removeClass("pulse-link"));
"secondPage"===m&&(c.text("2"),$(".gerry").addClass("animated fadeInLeft"),$(".gerrytext").addClass("animated fadeInRightBig"),d.css("color","#ebebeb"),g.css("color","#ebebeb"),a.css({color:"#333"}),$(".gerry").cycle({timeout:900,speed:900,fx:"fade",loop:1}),h.addClass("pulse-link"));"secondPage"!==m&&(g.css("color","#333"),h.removeClass("pulse-link"));"thirdPage"===m&&(c.text("3"),f.addClass("pulse-link"));"thirdPage"!==m&&f.removeClass("pulse-link");"fourthPage"===m&&(c.text("4"),l.addClass("pulse-link"));
"fourthPage"!==m&&l.removeClass("pulse-link");"fifthPage"===m&&(c.text("5"),k.addClass("pulse-link"));"fifthPage"!==m&&k.removeClass("pulse-link");"sixthPage"===m&&(c.text("6"),n.addClass("pulse-link"));"sixthPage"!==m&&n.removeClass("pulse-link");"seventhPage"===m&&(c.text("7"),r.addClass("pulse-link"));"seventhPage"!==m&&r.removeClass("pulse-link");"eighthPage"===m&&(c.text("8"),x.addClass("pulse-link"));"eighthPage"!==m&&x.removeClass("pulse-link");"ninthPage"===m&&(c.text("9"),y.addClass("pulse-link"));
"ninthPage"!==m&&y.removeClass("pulse-link");"tenthPage"===m&&(c.text("10"),L.addClass("pulse-link"));"tenthPage"!==m&&L.removeClass("pulse-link");"eleventhPage"===m&&(c.text("11"),S.addClass("pulse-link"));"eleventhPage"!==m&&S.removeClass("pulse-link");"twelfthPage"===m&&(c.text("12"),T.addClass("pulse-link"));"twelfthPage"!==m&&T.removeClass("pulse-link");"thirteenthPage"===m&&(c.text("13"),p.fadeOut(100),$("#section11").find(".slide").addClass("loadImage"),b.load(),N.fadeOut(100),u.fadeOut(100),
p.fadeOut(100),B.fadeOut(100),z.fadeOut(100),C.fadeOut(100),w.removeClass("pulse-link"),A.addClass("pulse-link"));"thirteenthPage"!==m&&A.removeClass("pulse-link");"fourteenthPage"===m&&(b.src="leb wohl edit-sm.mp3",b.volume=.3,b.autoPlay=!1,b.preLoad=!0,b.paused=!1,"boolean"==typeof b.loop?b.loop=!0:b.addEventListener("ended",function(){this.currentTime=0;this.play()},!1),b.play(),c.text("14"),$(".stop").on("click",function(){b.load()}),$(".play").on("click",function(){b.play()}),$(".fa-pause").on("click",
function(){b.paused?b.play():b.pause();$(this).toggleClass("pause")}),N.fadeIn("slow").birdman({speedup:!1,delay:0}),C.fadeIn().birdman({speedup:!1,delay:900}),u.fadeIn().birdman({speedup:!0,delay:300}),p.fadeIn(6E3),z.fadeIn(1E3),B.fadeIn(1E3),w.addClass("pulse-link"));"fourteenthPage"!==m&&(b.load(),b.paused=!0,N.fadeOut(100),u.fadeOut(100),p.fadeOut(100),B.fadeOut(100),z.fadeOut(100),C.fadeOut(100),w.removeClass("pulse-link"))}});$("#menu").click(function(){$(".menu-bars").toggleClass("open");
return $(".overlay").toggleClass("open")});return $(".overlay ul li a").click(function(){$(".overlay").removeClass("open");return $(".menu-bars").removeClass("open")})})}).call(this);